// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package fetcher

import (
	"encoding/json"

	"github.com/go-risk-it/go-risk-it/internal/ctx"
	mock "github.com/stretchr/testify/mock"
)

// NewPlayerFetcher creates a new instance of PlayerFetcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPlayerFetcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *PlayerFetcher {
	mock := &PlayerFetcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// PlayerFetcher is an autogenerated mock type for the PlayerFetcher type
type PlayerFetcher struct {
	mock.Mock
}

type PlayerFetcher_Expecter struct {
	mock *mock.Mock
}

func (_m *PlayerFetcher) EXPECT() *PlayerFetcher_Expecter {
	return &PlayerFetcher_Expecter{mock: &_m.Mock}
}

// FetchState provides a mock function for the type PlayerFetcher
func (_mock *PlayerFetcher) FetchState(ctx1 ctx.GameContext, stateChannel chan json.RawMessage) {
	_mock.Called(ctx1, stateChannel)
	return
}

// PlayerFetcher_FetchState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchState'
type PlayerFetcher_FetchState_Call struct {
	*mock.Call
}

// FetchState is a helper method to define mock.On call
//   - ctx1 ctx.GameContext
//   - stateChannel chan json.RawMessage
func (_e *PlayerFetcher_Expecter) FetchState(ctx1 interface{}, stateChannel interface{}) *PlayerFetcher_FetchState_Call {
	return &PlayerFetcher_FetchState_Call{Call: _e.mock.On("FetchState", ctx1, stateChannel)}
}

func (_c *PlayerFetcher_FetchState_Call) Run(run func(ctx1 ctx.GameContext, stateChannel chan json.RawMessage)) *PlayerFetcher_FetchState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 ctx.GameContext
		if args[0] != nil {
			arg0 = args[0].(ctx.GameContext)
		}
		var arg1 chan json.RawMessage
		if args[1] != nil {
			arg1 = args[1].(chan json.RawMessage)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *PlayerFetcher_FetchState_Call) Return() *PlayerFetcher_FetchState_Call {
	_c.Call.Return()
	return _c
}

func (_c *PlayerFetcher_FetchState_Call) RunAndReturn(run func(ctx1 ctx.GameContext, stateChannel chan json.RawMessage)) *PlayerFetcher_FetchState_Call {
	_c.Run(run)
	return _c
}
