// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package sqlc

import (
	"context"
)

type Querier interface {
	GetGame(ctx context.Context, id int64) (Game, error)
	GetPlayersByGameId(ctx context.Context, gameID int64) ([]Player, error)
	InsertGame(ctx context.Context) (int64, error)
	InsertPlayers(ctx context.Context, arg []InsertPlayersParams) (int64, error)
	InsertRegions(ctx context.Context, arg []InsertRegionsParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
