// Code generated by mockery v2.50.1. DO NOT EDIT.

package signals

import (
	context "context"

	lobbysignals "github.com/go-risk-it/go-risk-it/internal/logic/lobby/signals"
	mock "github.com/stretchr/testify/mock"

	signals "github.com/maniartech/signals"
)

// LobbyStateChangedSignal is an autogenerated mock type for the LobbyStateChangedSignal type
type LobbyStateChangedSignal struct {
	mock.Mock
}

type LobbyStateChangedSignal_Expecter struct {
	mock *mock.Mock
}

func (_m *LobbyStateChangedSignal) EXPECT() *LobbyStateChangedSignal_Expecter {
	return &LobbyStateChangedSignal_Expecter{mock: &_m.Mock}
}

// AddListener provides a mock function with given fields: handler, key
func (_m *LobbyStateChangedSignal) AddListener(handler signals.SignalListener[lobbysignals.LobbyStateChangedData], key ...string) int {
	_va := make([]interface{}, len(key))
	for _i := range key {
		_va[_i] = key[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, handler)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for AddListener")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func(signals.SignalListener[lobbysignals.LobbyStateChangedData], ...string) int); ok {
		r0 = rf(handler, key...)
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// LobbyStateChangedSignal_AddListener_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddListener'
type LobbyStateChangedSignal_AddListener_Call struct {
	*mock.Call
}

// AddListener is a helper method to define mock.On call
//   - handler signals.SignalListener[lobbysignals.LobbyStateChangedData]
//   - key ...string
func (_e *LobbyStateChangedSignal_Expecter) AddListener(handler interface{}, key ...interface{}) *LobbyStateChangedSignal_AddListener_Call {
	return &LobbyStateChangedSignal_AddListener_Call{Call: _e.mock.On("AddListener",
		append([]interface{}{handler}, key...)...)}
}

func (_c *LobbyStateChangedSignal_AddListener_Call) Run(run func(handler signals.SignalListener[lobbysignals.LobbyStateChangedData], key ...string)) *LobbyStateChangedSignal_AddListener_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]string, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(string)
			}
		}
		run(args[0].(signals.SignalListener[lobbysignals.LobbyStateChangedData]), variadicArgs...)
	})
	return _c
}

func (_c *LobbyStateChangedSignal_AddListener_Call) Return(_a0 int) *LobbyStateChangedSignal_AddListener_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *LobbyStateChangedSignal_AddListener_Call) RunAndReturn(run func(signals.SignalListener[lobbysignals.LobbyStateChangedData], ...string) int) *LobbyStateChangedSignal_AddListener_Call {
	_c.Call.Return(run)
	return _c
}

// Emit provides a mock function with given fields: ctx, payload
func (_m *LobbyStateChangedSignal) Emit(ctx context.Context, payload lobbysignals.LobbyStateChangedData) {
	_m.Called(ctx, payload)
}

// LobbyStateChangedSignal_Emit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Emit'
type LobbyStateChangedSignal_Emit_Call struct {
	*mock.Call
}

// Emit is a helper method to define mock.On call
//   - ctx context.Context
//   - payload lobbysignals.LobbyStateChangedData
func (_e *LobbyStateChangedSignal_Expecter) Emit(ctx interface{}, payload interface{}) *LobbyStateChangedSignal_Emit_Call {
	return &LobbyStateChangedSignal_Emit_Call{Call: _e.mock.On("Emit", ctx, payload)}
}

func (_c *LobbyStateChangedSignal_Emit_Call) Run(run func(ctx context.Context, payload lobbysignals.LobbyStateChangedData)) *LobbyStateChangedSignal_Emit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(lobbysignals.LobbyStateChangedData))
	})
	return _c
}

func (_c *LobbyStateChangedSignal_Emit_Call) Return() *LobbyStateChangedSignal_Emit_Call {
	_c.Call.Return()
	return _c
}

func (_c *LobbyStateChangedSignal_Emit_Call) RunAndReturn(run func(context.Context, lobbysignals.LobbyStateChangedData)) *LobbyStateChangedSignal_Emit_Call {
	_c.Run(run)
	return _c
}

// IsEmpty provides a mock function with no fields
func (_m *LobbyStateChangedSignal) IsEmpty() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsEmpty")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// LobbyStateChangedSignal_IsEmpty_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsEmpty'
type LobbyStateChangedSignal_IsEmpty_Call struct {
	*mock.Call
}

// IsEmpty is a helper method to define mock.On call
func (_e *LobbyStateChangedSignal_Expecter) IsEmpty() *LobbyStateChangedSignal_IsEmpty_Call {
	return &LobbyStateChangedSignal_IsEmpty_Call{Call: _e.mock.On("IsEmpty")}
}

func (_c *LobbyStateChangedSignal_IsEmpty_Call) Run(run func()) *LobbyStateChangedSignal_IsEmpty_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *LobbyStateChangedSignal_IsEmpty_Call) Return(_a0 bool) *LobbyStateChangedSignal_IsEmpty_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *LobbyStateChangedSignal_IsEmpty_Call) RunAndReturn(run func() bool) *LobbyStateChangedSignal_IsEmpty_Call {
	_c.Call.Return(run)
	return _c
}

// Len provides a mock function with no fields
func (_m *LobbyStateChangedSignal) Len() int {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Len")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// LobbyStateChangedSignal_Len_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Len'
type LobbyStateChangedSignal_Len_Call struct {
	*mock.Call
}

// Len is a helper method to define mock.On call
func (_e *LobbyStateChangedSignal_Expecter) Len() *LobbyStateChangedSignal_Len_Call {
	return &LobbyStateChangedSignal_Len_Call{Call: _e.mock.On("Len")}
}

func (_c *LobbyStateChangedSignal_Len_Call) Run(run func()) *LobbyStateChangedSignal_Len_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *LobbyStateChangedSignal_Len_Call) Return(_a0 int) *LobbyStateChangedSignal_Len_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *LobbyStateChangedSignal_Len_Call) RunAndReturn(run func() int) *LobbyStateChangedSignal_Len_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveListener provides a mock function with given fields: key
func (_m *LobbyStateChangedSignal) RemoveListener(key string) int {
	ret := _m.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for RemoveListener")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func(string) int); ok {
		r0 = rf(key)
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// LobbyStateChangedSignal_RemoveListener_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveListener'
type LobbyStateChangedSignal_RemoveListener_Call struct {
	*mock.Call
}

// RemoveListener is a helper method to define mock.On call
//   - key string
func (_e *LobbyStateChangedSignal_Expecter) RemoveListener(key interface{}) *LobbyStateChangedSignal_RemoveListener_Call {
	return &LobbyStateChangedSignal_RemoveListener_Call{Call: _e.mock.On("RemoveListener", key)}
}

func (_c *LobbyStateChangedSignal_RemoveListener_Call) Run(run func(key string)) *LobbyStateChangedSignal_RemoveListener_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *LobbyStateChangedSignal_RemoveListener_Call) Return(_a0 int) *LobbyStateChangedSignal_RemoveListener_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *LobbyStateChangedSignal_RemoveListener_Call) RunAndReturn(run func(string) int) *LobbyStateChangedSignal_RemoveListener_Call {
	_c.Call.Return(run)
	return _c
}

// Reset provides a mock function with no fields
func (_m *LobbyStateChangedSignal) Reset() {
	_m.Called()
}

// LobbyStateChangedSignal_Reset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reset'
type LobbyStateChangedSignal_Reset_Call struct {
	*mock.Call
}

// Reset is a helper method to define mock.On call
func (_e *LobbyStateChangedSignal_Expecter) Reset() *LobbyStateChangedSignal_Reset_Call {
	return &LobbyStateChangedSignal_Reset_Call{Call: _e.mock.On("Reset")}
}

func (_c *LobbyStateChangedSignal_Reset_Call) Run(run func()) *LobbyStateChangedSignal_Reset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *LobbyStateChangedSignal_Reset_Call) Return() *LobbyStateChangedSignal_Reset_Call {
	_c.Call.Return()
	return _c
}

func (_c *LobbyStateChangedSignal_Reset_Call) RunAndReturn(run func()) *LobbyStateChangedSignal_Reset_Call {
	_c.Run(run)
	return _c
}

// NewLobbyStateChangedSignal creates a new instance of LobbyStateChangedSignal. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLobbyStateChangedSignal(t interface {
	mock.TestingT
	Cleanup(func())
}) *LobbyStateChangedSignal {
	mock := &LobbyStateChangedSignal{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
