// Code generated by mockery v2.53.6. DO NOT EDIT.

package player

import (
	ctx "github.com/go-risk-it/go-risk-it/internal/ctx"
	db "github.com/go-risk-it/go-risk-it/internal/data/game/db"

	mock "github.com/stretchr/testify/mock"

	player "github.com/go-risk-it/go-risk-it/internal/logic/game/player"

	sqlc "github.com/go-risk-it/go-risk-it/internal/data/game/sqlc"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

type Service_Expecter struct {
	mock *mock.Mock
}

func (_m *Service) EXPECT() *Service_Expecter {
	return &Service_Expecter{mock: &_m.Mock}
}

// CreatePlayers provides a mock function with given fields: _a0, querier, gameID, players
func (_m *Service) CreatePlayers(_a0 ctx.GameContext, querier db.Querier, gameID int64, players []player.Player) ([]sqlc.GamePlayer, error) {
	ret := _m.Called(_a0, querier, gameID, players)

	if len(ret) == 0 {
		panic("no return value specified for CreatePlayers")
	}

	var r0 []sqlc.GamePlayer
	var r1 error
	if rf, ok := ret.Get(0).(func(ctx.GameContext, db.Querier, int64, []player.Player) ([]sqlc.GamePlayer, error)); ok {
		return rf(_a0, querier, gameID, players)
	}
	if rf, ok := ret.Get(0).(func(ctx.GameContext, db.Querier, int64, []player.Player) []sqlc.GamePlayer); ok {
		r0 = rf(_a0, querier, gameID, players)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]sqlc.GamePlayer)
		}
	}

	if rf, ok := ret.Get(1).(func(ctx.GameContext, db.Querier, int64, []player.Player) error); ok {
		r1 = rf(_a0, querier, gameID, players)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_CreatePlayers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePlayers'
type Service_CreatePlayers_Call struct {
	*mock.Call
}

// CreatePlayers is a helper method to define mock.On call
//   - _a0 ctx.GameContext
//   - querier db.Querier
//   - gameID int64
//   - players []player.Player
func (_e *Service_Expecter) CreatePlayers(_a0 interface{}, querier interface{}, gameID interface{}, players interface{}) *Service_CreatePlayers_Call {
	return &Service_CreatePlayers_Call{Call: _e.mock.On("CreatePlayers", _a0, querier, gameID, players)}
}

func (_c *Service_CreatePlayers_Call) Run(run func(_a0 ctx.GameContext, querier db.Querier, gameID int64, players []player.Player)) *Service_CreatePlayers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(ctx.GameContext), args[1].(db.Querier), args[2].(int64), args[3].([]player.Player))
	})
	return _c
}

func (_c *Service_CreatePlayers_Call) Return(_a0 []sqlc.GamePlayer, _a1 error) *Service_CreatePlayers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_CreatePlayers_Call) RunAndReturn(run func(ctx.GameContext, db.Querier, int64, []player.Player) ([]sqlc.GamePlayer, error)) *Service_CreatePlayers_Call {
	_c.Call.Return(run)
	return _c
}

// GetCurrentPlayer provides a mock function with given fields: _a0, querier
func (_m *Service) GetCurrentPlayer(_a0 ctx.GameContext, querier db.Querier) (sqlc.GamePlayer, error) {
	ret := _m.Called(_a0, querier)

	if len(ret) == 0 {
		panic("no return value specified for GetCurrentPlayer")
	}

	var r0 sqlc.GamePlayer
	var r1 error
	if rf, ok := ret.Get(0).(func(ctx.GameContext, db.Querier) (sqlc.GamePlayer, error)); ok {
		return rf(_a0, querier)
	}
	if rf, ok := ret.Get(0).(func(ctx.GameContext, db.Querier) sqlc.GamePlayer); ok {
		r0 = rf(_a0, querier)
	} else {
		r0 = ret.Get(0).(sqlc.GamePlayer)
	}

	if rf, ok := ret.Get(1).(func(ctx.GameContext, db.Querier) error); ok {
		r1 = rf(_a0, querier)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_GetCurrentPlayer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCurrentPlayer'
type Service_GetCurrentPlayer_Call struct {
	*mock.Call
}

// GetCurrentPlayer is a helper method to define mock.On call
//   - _a0 ctx.GameContext
//   - querier db.Querier
func (_e *Service_Expecter) GetCurrentPlayer(_a0 interface{}, querier interface{}) *Service_GetCurrentPlayer_Call {
	return &Service_GetCurrentPlayer_Call{Call: _e.mock.On("GetCurrentPlayer", _a0, querier)}
}

func (_c *Service_GetCurrentPlayer_Call) Run(run func(_a0 ctx.GameContext, querier db.Querier)) *Service_GetCurrentPlayer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(ctx.GameContext), args[1].(db.Querier))
	})
	return _c
}

func (_c *Service_GetCurrentPlayer_Call) Return(_a0 sqlc.GamePlayer, _a1 error) *Service_GetCurrentPlayer_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_GetCurrentPlayer_Call) RunAndReturn(run func(ctx.GameContext, db.Querier) (sqlc.GamePlayer, error)) *Service_GetCurrentPlayer_Call {
	_c.Call.Return(run)
	return _c
}

// GetNextPlayer provides a mock function with given fields: _a0, querier
func (_m *Service) GetNextPlayer(_a0 ctx.GameContext, querier db.Querier) (sqlc.GamePlayer, error) {
	ret := _m.Called(_a0, querier)

	if len(ret) == 0 {
		panic("no return value specified for GetNextPlayer")
	}

	var r0 sqlc.GamePlayer
	var r1 error
	if rf, ok := ret.Get(0).(func(ctx.GameContext, db.Querier) (sqlc.GamePlayer, error)); ok {
		return rf(_a0, querier)
	}
	if rf, ok := ret.Get(0).(func(ctx.GameContext, db.Querier) sqlc.GamePlayer); ok {
		r0 = rf(_a0, querier)
	} else {
		r0 = ret.Get(0).(sqlc.GamePlayer)
	}

	if rf, ok := ret.Get(1).(func(ctx.GameContext, db.Querier) error); ok {
		r1 = rf(_a0, querier)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_GetNextPlayer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNextPlayer'
type Service_GetNextPlayer_Call struct {
	*mock.Call
}

// GetNextPlayer is a helper method to define mock.On call
//   - _a0 ctx.GameContext
//   - querier db.Querier
func (_e *Service_Expecter) GetNextPlayer(_a0 interface{}, querier interface{}) *Service_GetNextPlayer_Call {
	return &Service_GetNextPlayer_Call{Call: _e.mock.On("GetNextPlayer", _a0, querier)}
}

func (_c *Service_GetNextPlayer_Call) Run(run func(_a0 ctx.GameContext, querier db.Querier)) *Service_GetNextPlayer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(ctx.GameContext), args[1].(db.Querier))
	})
	return _c
}

func (_c *Service_GetNextPlayer_Call) Return(_a0 sqlc.GamePlayer, _a1 error) *Service_GetNextPlayer_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_GetNextPlayer_Call) RunAndReturn(run func(ctx.GameContext, db.Querier) (sqlc.GamePlayer, error)) *Service_GetNextPlayer_Call {
	_c.Call.Return(run)
	return _c
}

// GetPlayers provides a mock function with given fields: _a0, querier
func (_m *Service) GetPlayers(_a0 ctx.GameContext, querier db.Querier) ([]sqlc.GamePlayer, error) {
	ret := _m.Called(_a0, querier)

	if len(ret) == 0 {
		panic("no return value specified for GetPlayers")
	}

	var r0 []sqlc.GamePlayer
	var r1 error
	if rf, ok := ret.Get(0).(func(ctx.GameContext, db.Querier) ([]sqlc.GamePlayer, error)); ok {
		return rf(_a0, querier)
	}
	if rf, ok := ret.Get(0).(func(ctx.GameContext, db.Querier) []sqlc.GamePlayer); ok {
		r0 = rf(_a0, querier)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]sqlc.GamePlayer)
		}
	}

	if rf, ok := ret.Get(1).(func(ctx.GameContext, db.Querier) error); ok {
		r1 = rf(_a0, querier)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_GetPlayers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPlayers'
type Service_GetPlayers_Call struct {
	*mock.Call
}

// GetPlayers is a helper method to define mock.On call
//   - _a0 ctx.GameContext
//   - querier db.Querier
func (_e *Service_Expecter) GetPlayers(_a0 interface{}, querier interface{}) *Service_GetPlayers_Call {
	return &Service_GetPlayers_Call{Call: _e.mock.On("GetPlayers", _a0, querier)}
}

func (_c *Service_GetPlayers_Call) Run(run func(_a0 ctx.GameContext, querier db.Querier)) *Service_GetPlayers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(ctx.GameContext), args[1].(db.Querier))
	})
	return _c
}

func (_c *Service_GetPlayers_Call) Return(_a0 []sqlc.GamePlayer, _a1 error) *Service_GetPlayers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_GetPlayers_Call) RunAndReturn(run func(ctx.GameContext, db.Querier) ([]sqlc.GamePlayer, error)) *Service_GetPlayers_Call {
	_c.Call.Return(run)
	return _c
}

// GetPlayersState provides a mock function with given fields: _a0
func (_m *Service) GetPlayersState(_a0 ctx.GameContext) ([]sqlc.GetPlayersStateRow, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for GetPlayersState")
	}

	var r0 []sqlc.GetPlayersStateRow
	var r1 error
	if rf, ok := ret.Get(0).(func(ctx.GameContext) ([]sqlc.GetPlayersStateRow, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(ctx.GameContext) []sqlc.GetPlayersStateRow); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]sqlc.GetPlayersStateRow)
		}
	}

	if rf, ok := ret.Get(1).(func(ctx.GameContext) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_GetPlayersState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPlayersState'
type Service_GetPlayersState_Call struct {
	*mock.Call
}

// GetPlayersState is a helper method to define mock.On call
//   - _a0 ctx.GameContext
func (_e *Service_Expecter) GetPlayersState(_a0 interface{}) *Service_GetPlayersState_Call {
	return &Service_GetPlayersState_Call{Call: _e.mock.On("GetPlayersState", _a0)}
}

func (_c *Service_GetPlayersState_Call) Run(run func(_a0 ctx.GameContext)) *Service_GetPlayersState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(ctx.GameContext))
	})
	return _c
}

func (_c *Service_GetPlayersState_Call) Return(_a0 []sqlc.GetPlayersStateRow, _a1 error) *Service_GetPlayersState_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_GetPlayersState_Call) RunAndReturn(run func(ctx.GameContext) ([]sqlc.GetPlayersStateRow, error)) *Service_GetPlayersState_Call {
	_c.Call.Return(run)
	return _c
}

// GetPlayersStateWithQuerier provides a mock function with given fields: _a0, querier
func (_m *Service) GetPlayersStateWithQuerier(_a0 ctx.GameContext, querier db.Querier) ([]sqlc.GetPlayersStateRow, error) {
	ret := _m.Called(_a0, querier)

	if len(ret) == 0 {
		panic("no return value specified for GetPlayersStateWithQuerier")
	}

	var r0 []sqlc.GetPlayersStateRow
	var r1 error
	if rf, ok := ret.Get(0).(func(ctx.GameContext, db.Querier) ([]sqlc.GetPlayersStateRow, error)); ok {
		return rf(_a0, querier)
	}
	if rf, ok := ret.Get(0).(func(ctx.GameContext, db.Querier) []sqlc.GetPlayersStateRow); ok {
		r0 = rf(_a0, querier)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]sqlc.GetPlayersStateRow)
		}
	}

	if rf, ok := ret.Get(1).(func(ctx.GameContext, db.Querier) error); ok {
		r1 = rf(_a0, querier)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_GetPlayersStateWithQuerier_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPlayersStateWithQuerier'
type Service_GetPlayersStateWithQuerier_Call struct {
	*mock.Call
}

// GetPlayersStateWithQuerier is a helper method to define mock.On call
//   - _a0 ctx.GameContext
//   - querier db.Querier
func (_e *Service_Expecter) GetPlayersStateWithQuerier(_a0 interface{}, querier interface{}) *Service_GetPlayersStateWithQuerier_Call {
	return &Service_GetPlayersStateWithQuerier_Call{Call: _e.mock.On("GetPlayersStateWithQuerier", _a0, querier)}
}

func (_c *Service_GetPlayersStateWithQuerier_Call) Run(run func(_a0 ctx.GameContext, querier db.Querier)) *Service_GetPlayersStateWithQuerier_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(ctx.GameContext), args[1].(db.Querier))
	})
	return _c
}

func (_c *Service_GetPlayersStateWithQuerier_Call) Return(_a0 []sqlc.GetPlayersStateRow, _a1 error) *Service_GetPlayersStateWithQuerier_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_GetPlayersStateWithQuerier_Call) RunAndReturn(run func(ctx.GameContext, db.Querier) ([]sqlc.GetPlayersStateRow, error)) *Service_GetPlayersStateWithQuerier_Call {
	_c.Call.Return(run)
	return _c
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
