// Code generated by mockery v2.40.1. DO NOT EDIT.

package region

import (
	context "context"

	board "github.com/tomfran/go-risk-it/internal/logic/board"

	db "github.com/tomfran/go-risk-it/internal/db"

	mock "github.com/stretchr/testify/mock"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// CreateRegions provides a mock function with given fields: ctx, q, players, regions
func (_m *MockService) CreateRegions(ctx context.Context, q db.Querier, players []db.Player, regions []board.Region) error {
	ret := _m.Called(ctx, q, players, regions)

	if len(ret) == 0 {
		panic("no return value specified for CreateRegions")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, db.Querier, []db.Player, []board.Region) error); ok {
		r0 = rf(ctx, q, players, regions)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_CreateRegions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRegions'
type MockService_CreateRegions_Call struct {
	*mock.Call
}

// CreateRegions is a helper method to define mock.On call
//   - ctx context.Context
//   - q db.Querier
//   - players []db.Player
//   - regions []board.Region
func (_e *MockService_Expecter) CreateRegions(ctx interface{}, q interface{}, players interface{}, regions interface{}) *MockService_CreateRegions_Call {
	return &MockService_CreateRegions_Call{Call: _e.mock.On("CreateRegions", ctx, q, players, regions)}
}

func (_c *MockService_CreateRegions_Call) Run(run func(ctx context.Context, q db.Querier, players []db.Player, regions []board.Region)) *MockService_CreateRegions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.Querier), args[2].([]db.Player), args[3].([]board.Region))
	})
	return _c
}

func (_c *MockService_CreateRegions_Call) Return(_a0 error) *MockService_CreateRegions_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_CreateRegions_Call) RunAndReturn(run func(context.Context, db.Querier, []db.Player, []board.Region) error) *MockService_CreateRegions_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
