// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package snapshot

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMissionDetail creates a new instance of MissionDetail. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMissionDetail(t interface {
	mock.TestingT
	Cleanup(func())
}) *MissionDetail {
	mock := &MissionDetail{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MissionDetail is an autogenerated mock type for the MissionDetail type
type MissionDetail struct {
	mock.Mock
}

type MissionDetail_Expecter struct {
	mock *mock.Mock
}

func (_m *MissionDetail) EXPECT() *MissionDetail_Expecter {
	return &MissionDetail_Expecter{mock: &_m.Mock}
}

// isMissionDetail provides a mock function for the type MissionDetail
func (_mock *MissionDetail) isMissionDetail() {
	_mock.Called()
	return
}

// MissionDetail_isMissionDetail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'isMissionDetail'
type MissionDetail_isMissionDetail_Call struct {
	*mock.Call
}

// isMissionDetail is a helper method to define mock.On call
func (_e *MissionDetail_Expecter) isMissionDetail() *MissionDetail_isMissionDetail_Call {
	return &MissionDetail_isMissionDetail_Call{Call: _e.mock.On("isMissionDetail")}
}

func (_c *MissionDetail_isMissionDetail_Call) Run(run func()) *MissionDetail_isMissionDetail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MissionDetail_isMissionDetail_Call) Return() *MissionDetail_isMissionDetail_Call {
	_c.Call.Return()
	return _c
}

func (_c *MissionDetail_isMissionDetail_Call) RunAndReturn(run func()) *MissionDetail_isMissionDetail_Call {
	_c.Run(run)
	return _c
}
