// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"context"
)

type Querier interface {
	CreateLobby(ctx context.Context) (int64, error)
	InsertParticipant(ctx context.Context, arg InsertParticipantParams) (int64, error)
	UpdateLobbyOwner(ctx context.Context, arg UpdateLobbyOwnerParams) error
}

var _ Querier = (*Queries)(nil)
