version: "2"
run:
  tests: true
linters:
  default: all
  disable:
    - containedctx
    - contextcheck
    - depguard
    - err113
    - exhaustruct
    - gochecknoglobals
    - iface
    - ireturn
    - mnd
    - funcorder
    - noinlineerr
    - wrapcheck
    - wsl
    - wsl_v5
  settings:
    exhaustive:
      default-signifies-exhaustive: true
    gocritic:
      disabled-checks:
        - singleCaseSwitch
    gosec:
      excludes:
        - G101
        - G404
    iface:
      enable:
        - identical
        - unused
        - opaque
    lll:
      line-length: 99
      tab-width: 4
    revive:
      rules:
        - name: blank-imports
          disabled: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dogsled
          - dupl
          - funlen
          - lll
        path: _test.go
    paths:
      - internal/upgradablerw_mutex
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - internal/upgradablerw_mutex
      - third_party$
      - builtin$
      - examples$
