version: "2"
run:
  tests: true
linters:
  default: all
  disable:
    - depguard
    - err113
    - exhaustruct
    - gochecknoglobals
    - iface
    - mnd
    - funcorder
    - noinlineerr
    - wsl
    - wsl_v5
  settings:
    exhaustive:
      default-signifies-exhaustive: true
    gocritic:
      disabled-checks:
        - singleCaseSwitch
    gosec:
      excludes:
        - G101
        - G404
    iface:
      enable:
        - identical
        - unused
        - opaque
    ireturn:
      allow:
        - error
        - stdlib
        - anon
        - empty
        - generic
        - github\.com/go-risk-it/go-risk-it/internal/ctx\..*
        - github\.com/go-risk-it/go-risk-it/internal/data/.*/db\.Querier
        - github\.com/jackc/pgx/v5\..*
        - go\.opentelemetry\.io/otel/.*
        - github\.com/go-risk-it/go-risk-it/internal/logic/game/signals\..*
        - github\.com/go-risk-it/go-risk-it/internal/logic/lobby/signals\..*
        - github\.com/go-risk-it/go-risk-it/internal/logic/game/board\..*
        - github\.com/go-risk-it/go-risk-it/internal/logic/game/mission.*
        - github\.com/go-risk-it/go-risk-it/internal/logic/game/move/attack/dice/roller\.Roller
        - github\.com/go-risk-it/go-risk-it/internal/logic/game/region/assignment\.Assigner
        - github\.com/go-risk-it/go-risk-it/internal/rand\.RNG
        - github\.com/maniartech/signals\.Signal
    lll:
      line-length: 99
      tab-width: 4
    revive:
      rules:
        - name: blank-imports
          disabled: true
    wrapcheck:
      ignore-sigs:
        - ".Errorf("
        - "errors.New("
        - "errors.Join("
        - ".Wrap("
        - ".Wrapf("
      ignore-package-globs:
        - github.com/go-risk-it/go-risk-it/*
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - contextcheck
        path: internal/web/(game|lobby)/signals/
      - linters:
          - dogsled
          - dupl
          - funlen
          - ireturn
          - lll
          - wrapcheck
        path: _test.go
    paths:
      - internal/upgradablerw_mutex
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - internal/upgradablerw_mutex
      - third_party$
      - builtin$
      - examples$
