with-expecter: True
inpackage: False
dir: mocks/{{ replaceAll .InterfaceDirRelative "internal" "internal_" }}
issue-845-fix: True
resolve-type-alias: False



mockname: "{{.InterfaceName}}"
outpkg: "{{.PackageName}}"
filename: "{{.InterfaceName}}.go"
all: True
packages:
  github.com/go-risk-it/go-risk-it/internal:
    config:
      recursive: True