all: true
dir: mocks/{{ replace "internal" "internal_" -1 .InterfaceDirRelative }}
filename: '{{.InterfaceName}}.go'
structname: '{{.InterfaceName}}'
pkgname: '{{.SrcPackageName}}'
template: testify
template-data:
  unroll-variadic: true
exclude:
  - github.com/go-risk-it/go-risk-it/internal/game/internal
  - github.com/go-risk-it/go-risk-it/internal/lobby/internal
packages:
  github.com/go-risk-it/go-risk-it/internal:
    config:
      recursive: true
