services:
  db:
    extends:
      file: supabase/docker-compose.yml
      service: db
  auth:
    extends:
      file: supabase/docker-compose.yml
      service: auth
  kong:
    extends:
      file: supabase/docker-compose.yml
      service: kong

  migrate:
    image: migrate/migrate:latest@sha256:f21c436af23c282f4516b00ba3e93bccf5c5fe5cd52530fd5c319a936998f539
    volumes:
      - ./internal/data/sqlc/migrations:/migrations
    command: -verbose -path=/migrations/ -database postgresql://postgres:password@postgres:5432/risk-it?sslmode=disable up
    depends_on:
      db:
        condition: service_healthy

  sqlc:
    image: sqlc/sqlc:latest@sha256:c2a7e80357000614571266cea1e4a0a9010ec03637998d71053c2ac6bb4b9f06
    env_file:
      - component-test/.env
    volumes:
      - ./:/src
    working_dir: /src
    command: generate
    depends_on:
      - migrate

  mockery:
    image: vektra/mockery:v2.46@sha256:3a8198900ae21bad2486bfcd4c63cc48e2ddc8876125b7d9488ab4ad6b11618f
    volumes:
      - ./:/src
    working_dir: /src
    depends_on:
      - sqlc

  risk-it:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy


volumes:
  postgres_data:
  socket:
  db-config:
