services:
  db:
    extends:
      file: supabase/docker-compose.yml
      service: db
  auth:
    extends:
      file: supabase/docker-compose.yml
      service: auth
  kong:
    extends:
      file: supabase/docker-compose.yml
      service: kong

  migrate:
    image: migrate/migrate:latest
    volumes:
      - ./internal/data/sqlc/migrations:/migrations
    command: -verbose -path=/migrations/ -database postgresql://postgres:password@postgres:5432/risk-it?sslmode=disable up
    depends_on:
      db:
        condition: service_healthy

  sqlc:
    image: sqlc/sqlc:latest
    env_file:
      - component-test/.env
    volumes:
      - ./:/src
    working_dir: /src
    command: generate
    depends_on:
      - migrate

  mockery:
    image: vektra/mockery:v2.50@sha256:2bb8c34143401c8565a663fbb1ca96d28ad6a0566e4c43e438ea394f4114bb93
    volumes:
      - ./:/src
    working_dir: /src
    depends_on:
      - sqlc

  risk-it:
    build:
      context: .
      dockerfile: docker/component-test/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy


volumes:
  postgres_data:
  socket:
  db-config:
