services:
  db:
    extends:
      file: supabase/docker-compose.yml
      service: db
  auth:
    extends:
      file: supabase/docker-compose.yml
      service: auth
  kong:
    extends:
      file: supabase/docker-compose.yml
      service: kong

  sqlc:
    image: sqlc/sqlc:latest@sha256:b8d1092c720438e093a231e75eba5d55b7696122f390292acabd5b6d3e986a12
    env_file:
      - component-test/.env
    volumes:
      - ./:/src
    working_dir: /src
    command: generate

  mockery:
    image: vektra/mockery:v2.53@sha256:77b5e3b443ae4b3517966f2844ec8f5f48b188d85d6f3ba28f4050816d0a032d
    volumes:
      - ./:/src
    working_dir: /src
    depends_on:
      - sqlc

  risk-it:
    build:
      context: .
      dockerfile: docker/component-test/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - OTEL_RESOURCE_ATTRIBUTES=service.name=risk-it,service.version=0.1.0
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://lgtm:4318
    depends_on:
      db:
        condition: service_healthy
      lgtm:
        condition: service_started

  lgtm:
    image: grafana/otel-lgtm:latest
    ports:
      - "3000:3000"
      - "4317:4317"
      - "4318:4318"
    volumes:
      - lgtm-data:/data
      - ./grafana/dashboards/dashboards.yml:/otel-lgtm/grafana/conf/provisioning/dashboards/go-risk-it.yaml
      - ./grafana/dashboards:/otel-lgtm/go-risk-it-dashboards
      - ./grafana/otelcol-extra.yaml:/otel-lgtm/otelcol-config.yaml

  postgres-exporter:
    image: quay.io/prometheuscommunity/postgres-exporter:latest
    environment:
      DATA_SOURCE_NAME: "postgresql://postgres:${DATABASE_PASSWORD}@db:5432/postgres?sslmode=disable"
    depends_on:
      db:
        condition: service_healthy
      lgtm:
        condition: service_started


volumes:
  postgres_data:
  socket:
  db-config:
  lgtm-data:
