// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service

import (
	"github.com/go-risk-it/go-risk-it/internal/game/api/snapshot"
	"github.com/go-risk-it/go-risk-it/internal/game/ctx"
	"github.com/go-risk-it/go-risk-it/internal/game/internal/data/db"
	"github.com/go-risk-it/go-risk-it/internal/game/internal/data/sqlc"
	"github.com/go-risk-it/go-risk-it/internal/game/internal/logic/move/service"
	mock "github.com/stretchr/testify/mock"
)

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService[T any, R any](t interface {
	mock.TestingT
	Cleanup(func())
},
) *Service[T, R] {
	mock := &Service[T, R]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Service is an autogenerated mock type for the Service type
type Service[T any, R any] struct {
	mock.Mock
}

type Service_Expecter[T any, R any] struct {
	mock *mock.Mock
}

func (_m *Service[T, R]) EXPECT() *Service_Expecter[T, R] {
	return &Service_Expecter[T, R]{mock: &_m.Mock}
}

// Advance provides a mock function for the type Service
func (_mock *Service[T, R]) Advance(ctx1 ctx.GameContext, querier db.Querier, targetPhase sqlc.GamePhaseType, performResult R, advCtx service.AdvanceContext) (service.AdvanceEffect, error) {
	ret := _mock.Called(ctx1, querier, targetPhase, performResult, advCtx)

	if len(ret) == 0 {
		panic("no return value specified for Advance")
	}

	var r0 service.AdvanceEffect
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(ctx.GameContext, db.Querier, sqlc.GamePhaseType, R, service.AdvanceContext) (service.AdvanceEffect, error)); ok {
		return returnFunc(ctx1, querier, targetPhase, performResult, advCtx)
	}
	if returnFunc, ok := ret.Get(0).(func(ctx.GameContext, db.Querier, sqlc.GamePhaseType, R, service.AdvanceContext) service.AdvanceEffect); ok {
		r0 = returnFunc(ctx1, querier, targetPhase, performResult, advCtx)
	} else {
		r0 = ret.Get(0).(service.AdvanceEffect)
	}
	if returnFunc, ok := ret.Get(1).(func(ctx.GameContext, db.Querier, sqlc.GamePhaseType, R, service.AdvanceContext) error); ok {
		r1 = returnFunc(ctx1, querier, targetPhase, performResult, advCtx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Service_Advance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Advance'
type Service_Advance_Call[T any, R any] struct {
	*mock.Call
}

// Advance is a helper method to define mock.On call
//   - ctx1 ctx.GameContext
//   - querier db.Querier
//   - targetPhase sqlc.GamePhaseType
//   - performResult R
//   - advCtx service.AdvanceContext
func (_e *Service_Expecter[T, R]) Advance(ctx1 interface{}, querier interface{}, targetPhase interface{}, performResult interface{}, advCtx interface{}) *Service_Advance_Call[T, R] {
	return &Service_Advance_Call[T, R]{Call: _e.mock.On("Advance", ctx1, querier, targetPhase, performResult, advCtx)}
}

func (_c *Service_Advance_Call[T, R]) Run(run func(ctx1 ctx.GameContext, querier db.Querier, targetPhase sqlc.GamePhaseType, performResult R, advCtx service.AdvanceContext)) *Service_Advance_Call[T, R] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 ctx.GameContext
		if args[0] != nil {
			arg0 = args[0].(ctx.GameContext)
		}
		var arg1 db.Querier
		if args[1] != nil {
			arg1 = args[1].(db.Querier)
		}
		var arg2 sqlc.GamePhaseType
		if args[2] != nil {
			arg2 = args[2].(sqlc.GamePhaseType)
		}
		var arg3 R
		if args[3] != nil {
			arg3 = args[3].(R)
		}
		var arg4 service.AdvanceContext
		if args[4] != nil {
			arg4 = args[4].(service.AdvanceContext)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *Service_Advance_Call[T, R]) Return(advanceEffect service.AdvanceEffect, err error) *Service_Advance_Call[T, R] {
	_c.Call.Return(advanceEffect, err)
	return _c
}

func (_c *Service_Advance_Call[T, R]) RunAndReturn(run func(ctx1 ctx.GameContext, querier db.Querier, targetPhase sqlc.GamePhaseType, performResult R, advCtx service.AdvanceContext) (service.AdvanceEffect, error)) *Service_Advance_Call[T, R] {
	_c.Call.Return(run)
	return _c
}

// Perform provides a mock function for the type Service
func (_mock *Service[T, R]) Perform(ctx1 ctx.GameContext, querier db.Querier, move T, prev *snapshot.CachedGameState) (R, service.MoveEffect, error) {
	ret := _mock.Called(ctx1, querier, move, prev)

	if len(ret) == 0 {
		panic("no return value specified for Perform")
	}

	var r0 R
	var r1 service.MoveEffect
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(ctx.GameContext, db.Querier, T, *snapshot.CachedGameState) (R, service.MoveEffect, error)); ok {
		return returnFunc(ctx1, querier, move, prev)
	}
	if returnFunc, ok := ret.Get(0).(func(ctx.GameContext, db.Querier, T, *snapshot.CachedGameState) R); ok {
		r0 = returnFunc(ctx1, querier, move, prev)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(R)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(ctx.GameContext, db.Querier, T, *snapshot.CachedGameState) service.MoveEffect); ok {
		r1 = returnFunc(ctx1, querier, move, prev)
	} else {
		r1 = ret.Get(1).(service.MoveEffect)
	}
	if returnFunc, ok := ret.Get(2).(func(ctx.GameContext, db.Querier, T, *snapshot.CachedGameState) error); ok {
		r2 = returnFunc(ctx1, querier, move, prev)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// Service_Perform_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Perform'
type Service_Perform_Call[T any, R any] struct {
	*mock.Call
}

// Perform is a helper method to define mock.On call
//   - ctx1 ctx.GameContext
//   - querier db.Querier
//   - move T
//   - prev *snapshot.CachedGameState
func (_e *Service_Expecter[T, R]) Perform(ctx1 interface{}, querier interface{}, move interface{}, prev interface{}) *Service_Perform_Call[T, R] {
	return &Service_Perform_Call[T, R]{Call: _e.mock.On("Perform", ctx1, querier, move, prev)}
}

func (_c *Service_Perform_Call[T, R]) Run(run func(ctx1 ctx.GameContext, querier db.Querier, move T, prev *snapshot.CachedGameState)) *Service_Perform_Call[T, R] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 ctx.GameContext
		if args[0] != nil {
			arg0 = args[0].(ctx.GameContext)
		}
		var arg1 db.Querier
		if args[1] != nil {
			arg1 = args[1].(db.Querier)
		}
		var arg2 T
		if args[2] != nil {
			arg2 = args[2].(T)
		}
		var arg3 *snapshot.CachedGameState
		if args[3] != nil {
			arg3 = args[3].(*snapshot.CachedGameState)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *Service_Perform_Call[T, R]) Return(v R, moveEffect service.MoveEffect, err error) *Service_Perform_Call[T, R] {
	_c.Call.Return(v, moveEffect, err)
	return _c
}

func (_c *Service_Perform_Call[T, R]) RunAndReturn(run func(ctx1 ctx.GameContext, querier db.Querier, move T, prev *snapshot.CachedGameState) (R, service.MoveEffect, error)) *Service_Perform_Call[T, R] {
	_c.Call.Return(run)
	return _c
}

// PhaseType provides a mock function for the type Service
func (_mock *Service[T, R]) PhaseType() sqlc.GamePhaseType {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for PhaseType")
	}

	var r0 sqlc.GamePhaseType
	if returnFunc, ok := ret.Get(0).(func() sqlc.GamePhaseType); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(sqlc.GamePhaseType)
	}
	return r0
}

// Service_PhaseType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PhaseType'
type Service_PhaseType_Call[T any, R any] struct {
	*mock.Call
}

// PhaseType is a helper method to define mock.On call
func (_e *Service_Expecter[T, R]) PhaseType() *Service_PhaseType_Call[T, R] {
	return &Service_PhaseType_Call[T, R]{Call: _e.mock.On("PhaseType")}
}

func (_c *Service_PhaseType_Call[T, R]) Run(run func()) *Service_PhaseType_Call[T, R] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Service_PhaseType_Call[T, R]) Return(gamePhaseType sqlc.GamePhaseType) *Service_PhaseType_Call[T, R] {
	_c.Call.Return(gamePhaseType)
	return _c
}

func (_c *Service_PhaseType_Call[T, R]) RunAndReturn(run func() sqlc.GamePhaseType) *Service_PhaseType_Call[T, R] {
	_c.Call.Return(run)
	return _c
}

// Walk provides a mock function for the type Service
func (_mock *Service[T, R]) Walk(wctx service.WalkContext) (sqlc.GamePhaseType, error) {
	ret := _mock.Called(wctx)

	if len(ret) == 0 {
		panic("no return value specified for Walk")
	}

	var r0 sqlc.GamePhaseType
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(service.WalkContext) (sqlc.GamePhaseType, error)); ok {
		return returnFunc(wctx)
	}
	if returnFunc, ok := ret.Get(0).(func(service.WalkContext) sqlc.GamePhaseType); ok {
		r0 = returnFunc(wctx)
	} else {
		r0 = ret.Get(0).(sqlc.GamePhaseType)
	}
	if returnFunc, ok := ret.Get(1).(func(service.WalkContext) error); ok {
		r1 = returnFunc(wctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Service_Walk_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Walk'
type Service_Walk_Call[T any, R any] struct {
	*mock.Call
}

// Walk is a helper method to define mock.On call
//   - wctx service.WalkContext
func (_e *Service_Expecter[T, R]) Walk(wctx interface{}) *Service_Walk_Call[T, R] {
	return &Service_Walk_Call[T, R]{Call: _e.mock.On("Walk", wctx)}
}

func (_c *Service_Walk_Call[T, R]) Run(run func(wctx service.WalkContext)) *Service_Walk_Call[T, R] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 service.WalkContext
		if args[0] != nil {
			arg0 = args[0].(service.WalkContext)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Service_Walk_Call[T, R]) Return(gamePhaseType sqlc.GamePhaseType, err error) *Service_Walk_Call[T, R] {
	_c.Call.Return(gamePhaseType, err)
	return _c
}

func (_c *Service_Walk_Call[T, R]) RunAndReturn(run func(wctx service.WalkContext) (sqlc.GamePhaseType, error)) *Service_Walk_Call[T, R] {
	_c.Call.Return(run)
	return _c
}
