// Code generated by mockery v2.43.1. DO NOT EDIT.

package controller

import (
	messaging "github.com/go-risk-it/go-risk-it/internal/api/game/messaging"
	ctx "github.com/go-risk-it/go-risk-it/internal/ctx"
	mock "github.com/stretchr/testify/mock"
)

// BoardController is an autogenerated mock type for the BoardController type
type BoardController struct {
	mock.Mock
}

type BoardController_Expecter struct {
	mock *mock.Mock
}

func (_m *BoardController) EXPECT() *BoardController_Expecter {
	return &BoardController_Expecter{mock: &_m.Mock}
}

// GetBoardState provides a mock function with given fields: _a0
func (_m *BoardController) GetBoardState(_a0 ctx.GameContext) (messaging.BoardState, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for GetBoardState")
	}

	var r0 messaging.BoardState
	var r1 error
	if rf, ok := ret.Get(0).(func(ctx.GameContext) (messaging.BoardState, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(ctx.GameContext) messaging.BoardState); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(messaging.BoardState)
	}

	if rf, ok := ret.Get(1).(func(ctx.GameContext) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BoardController_GetBoardState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBoardState'
type BoardController_GetBoardState_Call struct {
	*mock.Call
}

// GetBoardState is a helper method to define mock.On call
//   - _a0 ctx.GameContext
func (_e *BoardController_Expecter) GetBoardState(_a0 interface{}) *BoardController_GetBoardState_Call {
	return &BoardController_GetBoardState_Call{Call: _e.mock.On("GetBoardState", _a0)}
}

func (_c *BoardController_GetBoardState_Call) Run(run func(_a0 ctx.GameContext)) *BoardController_GetBoardState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(ctx.GameContext))
	})
	return _c
}

func (_c *BoardController_GetBoardState_Call) Return(_a0 messaging.BoardState, _a1 error) *BoardController_GetBoardState_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *BoardController_GetBoardState_Call) RunAndReturn(run func(ctx.GameContext) (messaging.BoardState, error)) *BoardController_GetBoardState_Call {
	_c.Call.Return(run)
	return _c
}

// NewBoardController creates a new instance of BoardController. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBoardController(t interface {
	mock.TestingT
	Cleanup(func())
}) *BoardController {
	mock := &BoardController{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
