// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package runner

import (
	"context"

	"github.com/go-risk-it/go-risk-it/internal/loadtest/client"
	mock "github.com/stretchr/testify/mock"
)

// NewRESTClient creates a new instance of RESTClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRESTClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *RESTClient {
	mock := &RESTClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// RESTClient is an autogenerated mock type for the RESTClient type
type RESTClient struct {
	mock.Mock
}

type RESTClient_Expecter struct {
	mock *mock.Mock
}

func (_m *RESTClient) EXPECT() *RESTClient_Expecter {
	return &RESTClient_Expecter{mock: &_m.Mock}
}

// Advance provides a mock function for the type RESTClient
func (_mock *RESTClient) Advance(ctx context.Context, gameID int64, currentPhase string) error {
	ret := _mock.Called(ctx, gameID, currentPhase)

	if len(ret) == 0 {
		panic("no return value specified for Advance")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string) error); ok {
		r0 = returnFunc(ctx, gameID, currentPhase)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// RESTClient_Advance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Advance'
type RESTClient_Advance_Call struct {
	*mock.Call
}

// Advance is a helper method to define mock.On call
//   - ctx context.Context
//   - gameID int64
//   - currentPhase string
func (_e *RESTClient_Expecter) Advance(ctx interface{}, gameID interface{}, currentPhase interface{}) *RESTClient_Advance_Call {
	return &RESTClient_Advance_Call{Call: _e.mock.On("Advance", ctx, gameID, currentPhase)}
}

func (_c *RESTClient_Advance_Call) Run(run func(ctx context.Context, gameID int64, currentPhase string)) *RESTClient_Advance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *RESTClient_Advance_Call) Return(err error) *RESTClient_Advance_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *RESTClient_Advance_Call) RunAndReturn(run func(ctx context.Context, gameID int64, currentPhase string) error) *RESTClient_Advance_Call {
	_c.Call.Return(run)
	return _c
}

// Attack provides a mock function for the type RESTClient
func (_mock *RESTClient) Attack(ctx context.Context, gameID int64, move client.AttackMove) error {
	ret := _mock.Called(ctx, gameID, move)

	if len(ret) == 0 {
		panic("no return value specified for Attack")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, client.AttackMove) error); ok {
		r0 = returnFunc(ctx, gameID, move)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// RESTClient_Attack_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Attack'
type RESTClient_Attack_Call struct {
	*mock.Call
}

// Attack is a helper method to define mock.On call
//   - ctx context.Context
//   - gameID int64
//   - move client.AttackMove
func (_e *RESTClient_Expecter) Attack(ctx interface{}, gameID interface{}, move interface{}) *RESTClient_Attack_Call {
	return &RESTClient_Attack_Call{Call: _e.mock.On("Attack", ctx, gameID, move)}
}

func (_c *RESTClient_Attack_Call) Run(run func(ctx context.Context, gameID int64, move client.AttackMove)) *RESTClient_Attack_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 client.AttackMove
		if args[2] != nil {
			arg2 = args[2].(client.AttackMove)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *RESTClient_Attack_Call) Return(err error) *RESTClient_Attack_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *RESTClient_Attack_Call) RunAndReturn(run func(ctx context.Context, gameID int64, move client.AttackMove) error) *RESTClient_Attack_Call {
	_c.Call.Return(run)
	return _c
}

// Conquer provides a mock function for the type RESTClient
func (_mock *RESTClient) Conquer(ctx context.Context, gameID int64, move client.ConquerMove) error {
	ret := _mock.Called(ctx, gameID, move)

	if len(ret) == 0 {
		panic("no return value specified for Conquer")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, client.ConquerMove) error); ok {
		r0 = returnFunc(ctx, gameID, move)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// RESTClient_Conquer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Conquer'
type RESTClient_Conquer_Call struct {
	*mock.Call
}

// Conquer is a helper method to define mock.On call
//   - ctx context.Context
//   - gameID int64
//   - move client.ConquerMove
func (_e *RESTClient_Expecter) Conquer(ctx interface{}, gameID interface{}, move interface{}) *RESTClient_Conquer_Call {
	return &RESTClient_Conquer_Call{Call: _e.mock.On("Conquer", ctx, gameID, move)}
}

func (_c *RESTClient_Conquer_Call) Run(run func(ctx context.Context, gameID int64, move client.ConquerMove)) *RESTClient_Conquer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 client.ConquerMove
		if args[2] != nil {
			arg2 = args[2].(client.ConquerMove)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *RESTClient_Conquer_Call) Return(err error) *RESTClient_Conquer_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *RESTClient_Conquer_Call) RunAndReturn(run func(ctx context.Context, gameID int64, move client.ConquerMove) error) *RESTClient_Conquer_Call {
	_c.Call.Return(run)
	return _c
}

// CreateGame provides a mock function for the type RESTClient
func (_mock *RESTClient) CreateGame(ctx context.Context, req client.CreateGameRequest) (int64, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateGame")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, client.CreateGameRequest) (int64, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, client.CreateGameRequest) int64); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, client.CreateGameRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RESTClient_CreateGame_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateGame'
type RESTClient_CreateGame_Call struct {
	*mock.Call
}

// CreateGame is a helper method to define mock.On call
//   - ctx context.Context
//   - req client.CreateGameRequest
func (_e *RESTClient_Expecter) CreateGame(ctx interface{}, req interface{}) *RESTClient_CreateGame_Call {
	return &RESTClient_CreateGame_Call{Call: _e.mock.On("CreateGame", ctx, req)}
}

func (_c *RESTClient_CreateGame_Call) Run(run func(ctx context.Context, req client.CreateGameRequest)) *RESTClient_CreateGame_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 client.CreateGameRequest
		if args[1] != nil {
			arg1 = args[1].(client.CreateGameRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *RESTClient_CreateGame_Call) Return(n int64, err error) *RESTClient_CreateGame_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *RESTClient_CreateGame_Call) RunAndReturn(run func(ctx context.Context, req client.CreateGameRequest) (int64, error)) *RESTClient_CreateGame_Call {
	_c.Call.Return(run)
	return _c
}

// Deploy provides a mock function for the type RESTClient
func (_mock *RESTClient) Deploy(ctx context.Context, gameID int64, move client.DeployMove) error {
	ret := _mock.Called(ctx, gameID, move)

	if len(ret) == 0 {
		panic("no return value specified for Deploy")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, client.DeployMove) error); ok {
		r0 = returnFunc(ctx, gameID, move)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// RESTClient_Deploy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Deploy'
type RESTClient_Deploy_Call struct {
	*mock.Call
}

// Deploy is a helper method to define mock.On call
//   - ctx context.Context
//   - gameID int64
//   - move client.DeployMove
func (_e *RESTClient_Expecter) Deploy(ctx interface{}, gameID interface{}, move interface{}) *RESTClient_Deploy_Call {
	return &RESTClient_Deploy_Call{Call: _e.mock.On("Deploy", ctx, gameID, move)}
}

func (_c *RESTClient_Deploy_Call) Run(run func(ctx context.Context, gameID int64, move client.DeployMove)) *RESTClient_Deploy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 client.DeployMove
		if args[2] != nil {
			arg2 = args[2].(client.DeployMove)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *RESTClient_Deploy_Call) Return(err error) *RESTClient_Deploy_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *RESTClient_Deploy_Call) RunAndReturn(run func(ctx context.Context, gameID int64, move client.DeployMove) error) *RESTClient_Deploy_Call {
	_c.Call.Return(run)
	return _c
}

// PlayCards provides a mock function for the type RESTClient
func (_mock *RESTClient) PlayCards(ctx context.Context, gameID int64, move client.CardsMove) error {
	ret := _mock.Called(ctx, gameID, move)

	if len(ret) == 0 {
		panic("no return value specified for PlayCards")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, client.CardsMove) error); ok {
		r0 = returnFunc(ctx, gameID, move)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// RESTClient_PlayCards_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PlayCards'
type RESTClient_PlayCards_Call struct {
	*mock.Call
}

// PlayCards is a helper method to define mock.On call
//   - ctx context.Context
//   - gameID int64
//   - move client.CardsMove
func (_e *RESTClient_Expecter) PlayCards(ctx interface{}, gameID interface{}, move interface{}) *RESTClient_PlayCards_Call {
	return &RESTClient_PlayCards_Call{Call: _e.mock.On("PlayCards", ctx, gameID, move)}
}

func (_c *RESTClient_PlayCards_Call) Run(run func(ctx context.Context, gameID int64, move client.CardsMove)) *RESTClient_PlayCards_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 client.CardsMove
		if args[2] != nil {
			arg2 = args[2].(client.CardsMove)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *RESTClient_PlayCards_Call) Return(err error) *RESTClient_PlayCards_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *RESTClient_PlayCards_Call) RunAndReturn(run func(ctx context.Context, gameID int64, move client.CardsMove) error) *RESTClient_PlayCards_Call {
	_c.Call.Return(run)
	return _c
}

// Reinforce provides a mock function for the type RESTClient
func (_mock *RESTClient) Reinforce(ctx context.Context, gameID int64, move client.ReinforceMove) error {
	ret := _mock.Called(ctx, gameID, move)

	if len(ret) == 0 {
		panic("no return value specified for Reinforce")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, client.ReinforceMove) error); ok {
		r0 = returnFunc(ctx, gameID, move)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// RESTClient_Reinforce_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reinforce'
type RESTClient_Reinforce_Call struct {
	*mock.Call
}

// Reinforce is a helper method to define mock.On call
//   - ctx context.Context
//   - gameID int64
//   - move client.ReinforceMove
func (_e *RESTClient_Expecter) Reinforce(ctx interface{}, gameID interface{}, move interface{}) *RESTClient_Reinforce_Call {
	return &RESTClient_Reinforce_Call{Call: _e.mock.On("Reinforce", ctx, gameID, move)}
}

func (_c *RESTClient_Reinforce_Call) Run(run func(ctx context.Context, gameID int64, move client.ReinforceMove)) *RESTClient_Reinforce_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 client.ReinforceMove
		if args[2] != nil {
			arg2 = args[2].(client.ReinforceMove)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *RESTClient_Reinforce_Call) Return(err error) *RESTClient_Reinforce_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *RESTClient_Reinforce_Call) RunAndReturn(run func(ctx context.Context, gameID int64, move client.ReinforceMove) error) *RESTClient_Reinforce_Call {
	_c.Call.Return(run)
	return _c
}
