// Code generated by mockery v2.43.1. DO NOT EDIT.

package orchestration

import (
	context "context"

	db "github.com/go-risk-it/go-risk-it/internal/data/db"
	mock "github.com/stretchr/testify/mock"

	sqlc "github.com/go-risk-it/go-risk-it/internal/data/sqlc"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

type Service_Expecter struct {
	mock *mock.Mock
}

func (_m *Service) EXPECT() *Service_Expecter {
	return &Service_Expecter{mock: &_m.Mock}
}

// PerformMove provides a mock function with given fields: ctx, gameID, userID, phase, perform
func (_m *Service) OrchestrateMove(ctx context.Context, gameID int64, userID string, phase sqlc.Phase, perform func(context.Context, db.Querier, *sqlc.Game) error) error {
	ret := _m.Called(ctx, gameID, userID, phase, perform)

	if len(ret) == 0 {
		panic("no return value specified for OrchestrateMove")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, sqlc.Phase, func(context.Context, db.Querier, *sqlc.Game) error) error); ok {
		r0 = rf(ctx, gameID, userID, phase, perform)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Service_PerformMove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OrchestrateMove'
type Service_PerformMove_Call struct {
	*mock.Call
}

// PerformMove is a helper method to define mock.On call
//   - ctx context.Context
//   - gameID int64
//   - userID string
//   - phase sqlc.Phase
//   - perform func(context.Context , db.Querier , *sqlc.Game) error
func (_e *Service_Expecter) PerformMove(ctx interface{}, gameID interface{}, userID interface{}, phase interface{}, perform interface{}) *Service_PerformMove_Call {
	return &Service_PerformMove_Call{Call: _e.mock.On("OrchestrateMove", ctx, gameID, userID, phase, perform)}
}

func (_c *Service_PerformMove_Call) Run(run func(ctx context.Context, gameID int64, userID string, phase sqlc.Phase, perform func(context.Context, db.Querier, *sqlc.Game) error)) *Service_PerformMove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(string), args[3].(sqlc.Phase), args[4].(func(context.Context, db.Querier, *sqlc.Game) error))
	})
	return _c
}

func (_c *Service_PerformMove_Call) Return(_a0 error) *Service_PerformMove_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Service_PerformMove_Call) RunAndReturn(run func(context.Context, int64, string, sqlc.Phase, func(context.Context, db.Querier, *sqlc.Game) error) error) *Service_PerformMove_Call {
	_c.Call.Return(run)
	return _c
}

// PerformMoveQ provides a mock function with given fields: ctx, querier, gameID, phase, userID, perform
func (_m *Service) OrchestrateMoveQ(ctx context.Context, querier db.Querier, gameID int64, phase sqlc.Phase, userID string, perform func(context.Context, db.Querier, *sqlc.Game) error) error {
	ret := _m.Called(ctx, querier, gameID, phase, userID, perform)

	if len(ret) == 0 {
		panic("no return value specified for OrchestrateMoveQ")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, db.Querier, int64, sqlc.Phase, string, func(context.Context, db.Querier, *sqlc.Game) error) error); ok {
		r0 = rf(ctx, querier, gameID, phase, userID, perform)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Service_PerformMoveQ_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OrchestrateMoveQ'
type Service_PerformMoveQ_Call struct {
	*mock.Call
}

// PerformMoveQ is a helper method to define mock.On call
//   - ctx context.Context
//   - querier db.Querier
//   - gameID int64
//   - phase sqlc.Phase
//   - userID string
//   - perform func(context.Context , db.Querier , *sqlc.Game) error
func (_e *Service_Expecter) PerformMoveQ(ctx interface{}, querier interface{}, gameID interface{}, phase interface{}, userID interface{}, perform interface{}) *Service_PerformMoveQ_Call {
	return &Service_PerformMoveQ_Call{Call: _e.mock.On("OrchestrateMoveQ", ctx, querier, gameID, phase, userID, perform)}
}

func (_c *Service_PerformMoveQ_Call) Run(run func(ctx context.Context, querier db.Querier, gameID int64, phase sqlc.Phase, userID string, perform func(context.Context, db.Querier, *sqlc.Game) error)) *Service_PerformMoveQ_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.Querier), args[2].(int64), args[3].(sqlc.Phase), args[4].(string), args[5].(func(context.Context, db.Querier, *sqlc.Game) error))
	})
	return _c
}

func (_c *Service_PerformMoveQ_Call) Return(_a0 error) *Service_PerformMoveQ_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Service_PerformMoveQ_Call) RunAndReturn(run func(context.Context, db.Querier, int64, sqlc.Phase, string, func(context.Context, db.Querier, *sqlc.Game) error) error) *Service_PerformMoveQ_Call {
	_c.Call.Return(run)
	return _c
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
