// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package game

import (
	"github.com/go-risk-it/go-risk-it/internal/game/api/snapshot"
	"github.com/go-risk-it/go-risk-it/internal/game/ctx"
	mock "github.com/stretchr/testify/mock"
)

// NewSnapshotReader creates a new instance of SnapshotReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSnapshotReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *SnapshotReader {
	mock := &SnapshotReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// SnapshotReader is an autogenerated mock type for the SnapshotReader type
type SnapshotReader struct {
	mock.Mock
}

type SnapshotReader_Expecter struct {
	mock *mock.Mock
}

func (_m *SnapshotReader) EXPECT() *SnapshotReader_Expecter {
	return &SnapshotReader_Expecter{mock: &_m.Mock}
}

// GetAllPrivateSnapshots provides a mock function for the type SnapshotReader
func (_mock *SnapshotReader) GetAllPrivateSnapshots(ctx1 ctx.GameContext) (map[string]*snapshot.PlayerPrivate, error) {
	ret := _mock.Called(ctx1)

	if len(ret) == 0 {
		panic("no return value specified for GetAllPrivateSnapshots")
	}

	var r0 map[string]*snapshot.PlayerPrivate
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(ctx.GameContext) (map[string]*snapshot.PlayerPrivate, error)); ok {
		return returnFunc(ctx1)
	}
	if returnFunc, ok := ret.Get(0).(func(ctx.GameContext) map[string]*snapshot.PlayerPrivate); ok {
		r0 = returnFunc(ctx1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]*snapshot.PlayerPrivate)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(ctx.GameContext) error); ok {
		r1 = returnFunc(ctx1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SnapshotReader_GetAllPrivateSnapshots_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllPrivateSnapshots'
type SnapshotReader_GetAllPrivateSnapshots_Call struct {
	*mock.Call
}

// GetAllPrivateSnapshots is a helper method to define mock.On call
//   - ctx1 ctx.GameContext
func (_e *SnapshotReader_Expecter) GetAllPrivateSnapshots(ctx1 interface{}) *SnapshotReader_GetAllPrivateSnapshots_Call {
	return &SnapshotReader_GetAllPrivateSnapshots_Call{Call: _e.mock.On("GetAllPrivateSnapshots", ctx1)}
}

func (_c *SnapshotReader_GetAllPrivateSnapshots_Call) Run(run func(ctx1 ctx.GameContext)) *SnapshotReader_GetAllPrivateSnapshots_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 ctx.GameContext
		if args[0] != nil {
			arg0 = args[0].(ctx.GameContext)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *SnapshotReader_GetAllPrivateSnapshots_Call) Return(stringToPlayerPrivate map[string]*snapshot.PlayerPrivate, err error) *SnapshotReader_GetAllPrivateSnapshots_Call {
	_c.Call.Return(stringToPlayerPrivate, err)
	return _c
}

func (_c *SnapshotReader_GetAllPrivateSnapshots_Call) RunAndReturn(run func(ctx1 ctx.GameContext) (map[string]*snapshot.PlayerPrivate, error)) *SnapshotReader_GetAllPrivateSnapshots_Call {
	_c.Call.Return(run)
	return _c
}

// GetPublicSnapshot provides a mock function for the type SnapshotReader
func (_mock *SnapshotReader) GetPublicSnapshot(ctx1 ctx.GameContext) (*snapshot.GameSnapshot, error) {
	ret := _mock.Called(ctx1)

	if len(ret) == 0 {
		panic("no return value specified for GetPublicSnapshot")
	}

	var r0 *snapshot.GameSnapshot
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(ctx.GameContext) (*snapshot.GameSnapshot, error)); ok {
		return returnFunc(ctx1)
	}
	if returnFunc, ok := ret.Get(0).(func(ctx.GameContext) *snapshot.GameSnapshot); ok {
		r0 = returnFunc(ctx1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*snapshot.GameSnapshot)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(ctx.GameContext) error); ok {
		r1 = returnFunc(ctx1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SnapshotReader_GetPublicSnapshot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPublicSnapshot'
type SnapshotReader_GetPublicSnapshot_Call struct {
	*mock.Call
}

// GetPublicSnapshot is a helper method to define mock.On call
//   - ctx1 ctx.GameContext
func (_e *SnapshotReader_Expecter) GetPublicSnapshot(ctx1 interface{}) *SnapshotReader_GetPublicSnapshot_Call {
	return &SnapshotReader_GetPublicSnapshot_Call{Call: _e.mock.On("GetPublicSnapshot", ctx1)}
}

func (_c *SnapshotReader_GetPublicSnapshot_Call) Run(run func(ctx1 ctx.GameContext)) *SnapshotReader_GetPublicSnapshot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 ctx.GameContext
		if args[0] != nil {
			arg0 = args[0].(ctx.GameContext)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *SnapshotReader_GetPublicSnapshot_Call) Return(gameSnapshot *snapshot.GameSnapshot, err error) *SnapshotReader_GetPublicSnapshot_Call {
	_c.Call.Return(gameSnapshot, err)
	return _c
}

func (_c *SnapshotReader_GetPublicSnapshot_Call) RunAndReturn(run func(ctx1 ctx.GameContext) (*snapshot.GameSnapshot, error)) *SnapshotReader_GetPublicSnapshot_Call {
	_c.Call.Return(run)
	return _c
}
