// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package game

import (
	"context"

	"github.com/go-risk-it/go-risk-it/internal/game/api/snapshot"
	mock "github.com/stretchr/testify/mock"
)

// NewStatePublisher creates a new instance of StatePublisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStatePublisher(t interface {
	mock.TestingT
	Cleanup(func())
}) *StatePublisher {
	mock := &StatePublisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// StatePublisher is an autogenerated mock type for the StatePublisher type
type StatePublisher struct {
	mock.Mock
}

type StatePublisher_Expecter struct {
	mock *mock.Mock
}

func (_m *StatePublisher) EXPECT() *StatePublisher_Expecter {
	return &StatePublisher_Expecter{mock: &_m.Mock}
}

// PublishState provides a mock function for the type StatePublisher
func (_mock *StatePublisher) PublishState(ctx context.Context, playerUserID string, view *snapshot.PlayerView) error {
	ret := _mock.Called(ctx, playerUserID, view)

	if len(ret) == 0 {
		panic("no return value specified for PublishState")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *snapshot.PlayerView) error); ok {
		r0 = returnFunc(ctx, playerUserID, view)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// StatePublisher_PublishState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishState'
type StatePublisher_PublishState_Call struct {
	*mock.Call
}

// PublishState is a helper method to define mock.On call
//   - ctx context.Context
//   - playerUserID string
//   - view *snapshot.PlayerView
func (_e *StatePublisher_Expecter) PublishState(ctx interface{}, playerUserID interface{}, view interface{}) *StatePublisher_PublishState_Call {
	return &StatePublisher_PublishState_Call{Call: _e.mock.On("PublishState", ctx, playerUserID, view)}
}

func (_c *StatePublisher_PublishState_Call) Run(run func(ctx context.Context, playerUserID string, view *snapshot.PlayerView)) *StatePublisher_PublishState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *snapshot.PlayerView
		if args[2] != nil {
			arg2 = args[2].(*snapshot.PlayerView)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *StatePublisher_PublishState_Call) Return(err error) *StatePublisher_PublishState_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *StatePublisher_PublishState_Call) RunAndReturn(run func(ctx context.Context, playerUserID string, view *snapshot.PlayerView) error) *StatePublisher_PublishState_Call {
	_c.Call.Return(run)
	return _c
}
