// Code generated by mockery v2.53.6. DO NOT EDIT.

package region

import (
	context "context"

	ctx "github.com/go-risk-it/go-risk-it/internal/ctx"
	db "github.com/go-risk-it/go-risk-it/internal/data/game/db"

	mock "github.com/stretchr/testify/mock"

	sqlc "github.com/go-risk-it/go-risk-it/internal/data/game/sqlc"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

type Service_Expecter struct {
	mock *mock.Mock
}

func (_m *Service) EXPECT() *Service_Expecter {
	return &Service_Expecter{mock: &_m.Mock}
}

// CreateRegions provides a mock function with given fields: _a0, querier, players, regions
func (_m *Service) CreateRegions(_a0 context.Context, querier db.Querier, players []sqlc.GamePlayer, regions []string) error {
	ret := _m.Called(_a0, querier, players, regions)

	if len(ret) == 0 {
		panic("no return value specified for CreateRegions")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, db.Querier, []sqlc.GamePlayer, []string) error); ok {
		r0 = rf(_a0, querier, players, regions)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Service_CreateRegions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRegions'
type Service_CreateRegions_Call struct {
	*mock.Call
}

// CreateRegions is a helper method to define mock.On call
//   - _a0 context.Context
//   - querier db.Querier
//   - players []sqlc.GamePlayer
//   - regions []string
func (_e *Service_Expecter) CreateRegions(_a0 interface{}, querier interface{}, players interface{}, regions interface{}) *Service_CreateRegions_Call {
	return &Service_CreateRegions_Call{Call: _e.mock.On("CreateRegions", _a0, querier, players, regions)}
}

func (_c *Service_CreateRegions_Call) Run(run func(_a0 context.Context, querier db.Querier, players []sqlc.GamePlayer, regions []string)) *Service_CreateRegions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.Querier), args[2].([]sqlc.GamePlayer), args[3].([]string))
	})
	return _c
}

func (_c *Service_CreateRegions_Call) Return(_a0 error) *Service_CreateRegions_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Service_CreateRegions_Call) RunAndReturn(run func(context.Context, db.Querier, []sqlc.GamePlayer, []string) error) *Service_CreateRegions_Call {
	_c.Call.Return(run)
	return _c
}

// GetPlayerRegions provides a mock function with given fields: _a0, querier
func (_m *Service) GetPlayerRegions(_a0 ctx.GameContext, querier db.Querier) ([]sqlc.GetRegionsByGameRow, error) {
	ret := _m.Called(_a0, querier)

	if len(ret) == 0 {
		panic("no return value specified for GetPlayerRegions")
	}

	var r0 []sqlc.GetRegionsByGameRow
	var r1 error
	if rf, ok := ret.Get(0).(func(ctx.GameContext, db.Querier) ([]sqlc.GetRegionsByGameRow, error)); ok {
		return rf(_a0, querier)
	}
	if rf, ok := ret.Get(0).(func(ctx.GameContext, db.Querier) []sqlc.GetRegionsByGameRow); ok {
		r0 = rf(_a0, querier)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]sqlc.GetRegionsByGameRow)
		}
	}

	if rf, ok := ret.Get(1).(func(ctx.GameContext, db.Querier) error); ok {
		r1 = rf(_a0, querier)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_GetPlayerRegions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPlayerRegions'
type Service_GetPlayerRegions_Call struct {
	*mock.Call
}

// GetPlayerRegions is a helper method to define mock.On call
//   - _a0 ctx.GameContext
//   - querier db.Querier
func (_e *Service_Expecter) GetPlayerRegions(_a0 interface{}, querier interface{}) *Service_GetPlayerRegions_Call {
	return &Service_GetPlayerRegions_Call{Call: _e.mock.On("GetPlayerRegions", _a0, querier)}
}

func (_c *Service_GetPlayerRegions_Call) Run(run func(_a0 ctx.GameContext, querier db.Querier)) *Service_GetPlayerRegions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(ctx.GameContext), args[1].(db.Querier))
	})
	return _c
}

func (_c *Service_GetPlayerRegions_Call) Return(_a0 []sqlc.GetRegionsByGameRow, _a1 error) *Service_GetPlayerRegions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_GetPlayerRegions_Call) RunAndReturn(run func(ctx.GameContext, db.Querier) ([]sqlc.GetRegionsByGameRow, error)) *Service_GetPlayerRegions_Call {
	_c.Call.Return(run)
	return _c
}

// GetRegion provides a mock function with given fields: _a0, querier, _a2
func (_m *Service) GetRegion(_a0 ctx.GameContext, querier db.Querier, _a2 string) (*sqlc.GetRegionsByGameRow, error) {
	ret := _m.Called(_a0, querier, _a2)

	if len(ret) == 0 {
		panic("no return value specified for GetRegion")
	}

	var r0 *sqlc.GetRegionsByGameRow
	var r1 error
	if rf, ok := ret.Get(0).(func(ctx.GameContext, db.Querier, string) (*sqlc.GetRegionsByGameRow, error)); ok {
		return rf(_a0, querier, _a2)
	}
	if rf, ok := ret.Get(0).(func(ctx.GameContext, db.Querier, string) *sqlc.GetRegionsByGameRow); ok {
		r0 = rf(_a0, querier, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sqlc.GetRegionsByGameRow)
		}
	}

	if rf, ok := ret.Get(1).(func(ctx.GameContext, db.Querier, string) error); ok {
		r1 = rf(_a0, querier, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_GetRegion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRegion'
type Service_GetRegion_Call struct {
	*mock.Call
}

// GetRegion is a helper method to define mock.On call
//   - _a0 ctx.GameContext
//   - querier db.Querier
//   - _a2 string
func (_e *Service_Expecter) GetRegion(_a0 interface{}, querier interface{}, _a2 interface{}) *Service_GetRegion_Call {
	return &Service_GetRegion_Call{Call: _e.mock.On("GetRegion", _a0, querier, _a2)}
}

func (_c *Service_GetRegion_Call) Run(run func(_a0 ctx.GameContext, querier db.Querier, _a2 string)) *Service_GetRegion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(ctx.GameContext), args[1].(db.Querier), args[2].(string))
	})
	return _c
}

func (_c *Service_GetRegion_Call) Return(_a0 *sqlc.GetRegionsByGameRow, _a1 error) *Service_GetRegion_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_GetRegion_Call) RunAndReturn(run func(ctx.GameContext, db.Querier, string) (*sqlc.GetRegionsByGameRow, error)) *Service_GetRegion_Call {
	_c.Call.Return(run)
	return _c
}

// GetRegions provides a mock function with given fields: _a0
func (_m *Service) GetRegions(_a0 ctx.GameContext) ([]sqlc.GetRegionsByGameRow, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for GetRegions")
	}

	var r0 []sqlc.GetRegionsByGameRow
	var r1 error
	if rf, ok := ret.Get(0).(func(ctx.GameContext) ([]sqlc.GetRegionsByGameRow, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(ctx.GameContext) []sqlc.GetRegionsByGameRow); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]sqlc.GetRegionsByGameRow)
		}
	}

	if rf, ok := ret.Get(1).(func(ctx.GameContext) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_GetRegions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRegions'
type Service_GetRegions_Call struct {
	*mock.Call
}

// GetRegions is a helper method to define mock.On call
//   - _a0 ctx.GameContext
func (_e *Service_Expecter) GetRegions(_a0 interface{}) *Service_GetRegions_Call {
	return &Service_GetRegions_Call{Call: _e.mock.On("GetRegions", _a0)}
}

func (_c *Service_GetRegions_Call) Run(run func(_a0 ctx.GameContext)) *Service_GetRegions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(ctx.GameContext))
	})
	return _c
}

func (_c *Service_GetRegions_Call) Return(_a0 []sqlc.GetRegionsByGameRow, _a1 error) *Service_GetRegions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_GetRegions_Call) RunAndReturn(run func(ctx.GameContext) ([]sqlc.GetRegionsByGameRow, error)) *Service_GetRegions_Call {
	_c.Call.Return(run)
	return _c
}

// GetRegionsControlledByPlayer provides a mock function with given fields: _a0, querier, playerID
func (_m *Service) GetRegionsControlledByPlayer(_a0 ctx.GameContext, querier db.Querier, playerID int64) ([]sqlc.GameRegion, error) {
	ret := _m.Called(_a0, querier, playerID)

	if len(ret) == 0 {
		panic("no return value specified for GetRegionsControlledByPlayer")
	}

	var r0 []sqlc.GameRegion
	var r1 error
	if rf, ok := ret.Get(0).(func(ctx.GameContext, db.Querier, int64) ([]sqlc.GameRegion, error)); ok {
		return rf(_a0, querier, playerID)
	}
	if rf, ok := ret.Get(0).(func(ctx.GameContext, db.Querier, int64) []sqlc.GameRegion); ok {
		r0 = rf(_a0, querier, playerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]sqlc.GameRegion)
		}
	}

	if rf, ok := ret.Get(1).(func(ctx.GameContext, db.Querier, int64) error); ok {
		r1 = rf(_a0, querier, playerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_GetRegionsControlledByPlayer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRegionsControlledByPlayer'
type Service_GetRegionsControlledByPlayer_Call struct {
	*mock.Call
}

// GetRegionsControlledByPlayer is a helper method to define mock.On call
//   - _a0 ctx.GameContext
//   - querier db.Querier
//   - playerID int64
func (_e *Service_Expecter) GetRegionsControlledByPlayer(_a0 interface{}, querier interface{}, playerID interface{}) *Service_GetRegionsControlledByPlayer_Call {
	return &Service_GetRegionsControlledByPlayer_Call{Call: _e.mock.On("GetRegionsControlledByPlayer", _a0, querier, playerID)}
}

func (_c *Service_GetRegionsControlledByPlayer_Call) Run(run func(_a0 ctx.GameContext, querier db.Querier, playerID int64)) *Service_GetRegionsControlledByPlayer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(ctx.GameContext), args[1].(db.Querier), args[2].(int64))
	})
	return _c
}

func (_c *Service_GetRegionsControlledByPlayer_Call) Return(_a0 []sqlc.GameRegion, _a1 error) *Service_GetRegionsControlledByPlayer_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_GetRegionsControlledByPlayer_Call) RunAndReturn(run func(ctx.GameContext, db.Querier, int64) ([]sqlc.GameRegion, error)) *Service_GetRegionsControlledByPlayer_Call {
	_c.Call.Return(run)
	return _c
}

// GetRegionsWithQuerier provides a mock function with given fields: _a0, querier
func (_m *Service) GetRegionsWithQuerier(_a0 ctx.GameContext, querier db.Querier) ([]sqlc.GetRegionsByGameRow, error) {
	ret := _m.Called(_a0, querier)

	if len(ret) == 0 {
		panic("no return value specified for GetRegionsWithQuerier")
	}

	var r0 []sqlc.GetRegionsByGameRow
	var r1 error
	if rf, ok := ret.Get(0).(func(ctx.GameContext, db.Querier) ([]sqlc.GetRegionsByGameRow, error)); ok {
		return rf(_a0, querier)
	}
	if rf, ok := ret.Get(0).(func(ctx.GameContext, db.Querier) []sqlc.GetRegionsByGameRow); ok {
		r0 = rf(_a0, querier)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]sqlc.GetRegionsByGameRow)
		}
	}

	if rf, ok := ret.Get(1).(func(ctx.GameContext, db.Querier) error); ok {
		r1 = rf(_a0, querier)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_GetRegionsWithQuerier_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRegionsWithQuerier'
type Service_GetRegionsWithQuerier_Call struct {
	*mock.Call
}

// GetRegionsWithQuerier is a helper method to define mock.On call
//   - _a0 ctx.GameContext
//   - querier db.Querier
func (_e *Service_Expecter) GetRegionsWithQuerier(_a0 interface{}, querier interface{}) *Service_GetRegionsWithQuerier_Call {
	return &Service_GetRegionsWithQuerier_Call{Call: _e.mock.On("GetRegionsWithQuerier", _a0, querier)}
}

func (_c *Service_GetRegionsWithQuerier_Call) Run(run func(_a0 ctx.GameContext, querier db.Querier)) *Service_GetRegionsWithQuerier_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(ctx.GameContext), args[1].(db.Querier))
	})
	return _c
}

func (_c *Service_GetRegionsWithQuerier_Call) Return(_a0 []sqlc.GetRegionsByGameRow, _a1 error) *Service_GetRegionsWithQuerier_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_GetRegionsWithQuerier_Call) RunAndReturn(run func(ctx.GameContext, db.Querier) ([]sqlc.GetRegionsByGameRow, error)) *Service_GetRegionsWithQuerier_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateRegionOwner provides a mock function with given fields: _a0, querier, _a2
func (_m *Service) UpdateRegionOwner(_a0 ctx.GameContext, querier db.Querier, _a2 *sqlc.GetRegionsByGameRow) (int64, error) {
	ret := _m.Called(_a0, querier, _a2)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRegionOwner")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(ctx.GameContext, db.Querier, *sqlc.GetRegionsByGameRow) (int64, error)); ok {
		return rf(_a0, querier, _a2)
	}
	if rf, ok := ret.Get(0).(func(ctx.GameContext, db.Querier, *sqlc.GetRegionsByGameRow) int64); ok {
		r0 = rf(_a0, querier, _a2)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(ctx.GameContext, db.Querier, *sqlc.GetRegionsByGameRow) error); ok {
		r1 = rf(_a0, querier, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_UpdateRegionOwner_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateRegionOwner'
type Service_UpdateRegionOwner_Call struct {
	*mock.Call
}

// UpdateRegionOwner is a helper method to define mock.On call
//   - _a0 ctx.GameContext
//   - querier db.Querier
//   - _a2 *sqlc.GetRegionsByGameRow
func (_e *Service_Expecter) UpdateRegionOwner(_a0 interface{}, querier interface{}, _a2 interface{}) *Service_UpdateRegionOwner_Call {
	return &Service_UpdateRegionOwner_Call{Call: _e.mock.On("UpdateRegionOwner", _a0, querier, _a2)}
}

func (_c *Service_UpdateRegionOwner_Call) Run(run func(_a0 ctx.GameContext, querier db.Querier, _a2 *sqlc.GetRegionsByGameRow)) *Service_UpdateRegionOwner_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(ctx.GameContext), args[1].(db.Querier), args[2].(*sqlc.GetRegionsByGameRow))
	})
	return _c
}

func (_c *Service_UpdateRegionOwner_Call) Return(_a0 int64, _a1 error) *Service_UpdateRegionOwner_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_UpdateRegionOwner_Call) RunAndReturn(run func(ctx.GameContext, db.Querier, *sqlc.GetRegionsByGameRow) (int64, error)) *Service_UpdateRegionOwner_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTroopsInRegion provides a mock function with given fields: _a0, querier, _a2, troopsToAdd
func (_m *Service) UpdateTroopsInRegion(_a0 ctx.GameContext, querier db.Querier, _a2 *sqlc.GetRegionsByGameRow, troopsToAdd int64) error {
	ret := _m.Called(_a0, querier, _a2, troopsToAdd)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTroopsInRegion")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(ctx.GameContext, db.Querier, *sqlc.GetRegionsByGameRow, int64) error); ok {
		r0 = rf(_a0, querier, _a2, troopsToAdd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Service_UpdateTroopsInRegion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTroopsInRegion'
type Service_UpdateTroopsInRegion_Call struct {
	*mock.Call
}

// UpdateTroopsInRegion is a helper method to define mock.On call
//   - _a0 ctx.GameContext
//   - querier db.Querier
//   - _a2 *sqlc.GetRegionsByGameRow
//   - troopsToAdd int64
func (_e *Service_Expecter) UpdateTroopsInRegion(_a0 interface{}, querier interface{}, _a2 interface{}, troopsToAdd interface{}) *Service_UpdateTroopsInRegion_Call {
	return &Service_UpdateTroopsInRegion_Call{Call: _e.mock.On("UpdateTroopsInRegion", _a0, querier, _a2, troopsToAdd)}
}

func (_c *Service_UpdateTroopsInRegion_Call) Run(run func(_a0 ctx.GameContext, querier db.Querier, _a2 *sqlc.GetRegionsByGameRow, troopsToAdd int64)) *Service_UpdateTroopsInRegion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(ctx.GameContext), args[1].(db.Querier), args[2].(*sqlc.GetRegionsByGameRow), args[3].(int64))
	})
	return _c
}

func (_c *Service_UpdateTroopsInRegion_Call) Return(_a0 error) *Service_UpdateTroopsInRegion_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Service_UpdateTroopsInRegion_Call) RunAndReturn(run func(ctx.GameContext, db.Querier, *sqlc.GetRegionsByGameRow, int64) error) *Service_UpdateTroopsInRegion_Call {
	_c.Call.Return(run)
	return _c
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
