version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: risk-it
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/tmp/postgresql/data

  flyway:
    image: flyway/flyway:latest
    depends_on:
      - postgres
    volumes:
      - ./sql:/flyway/sql
    command: -url=jdbc:postgresql://postgres:5432/risk-it -user=postgres -password=password -connectRetries=10 migrate

volumes:
  postgres_data:
