// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package db

import (
	"context"

	"github.com/go-risk-it/go-risk-it/internal/lobby/internal/data/db"
	"github.com/go-risk-it/go-risk-it/internal/lobby/internal/data/sqlc"
	"github.com/jackc/pgx/v5"
	mock "github.com/stretchr/testify/mock"
)

// NewQuerier creates a new instance of Querier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewQuerier(t interface {
	mock.TestingT
	Cleanup(func())
},
) *Querier {
	mock := &Querier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Querier is an autogenerated mock type for the Querier type
type Querier struct {
	mock.Mock
}

type Querier_Expecter struct {
	mock *mock.Mock
}

func (_m *Querier) EXPECT() *Querier_Expecter {
	return &Querier_Expecter{mock: &_m.Mock}
}

// BeginTx provides a mock function for the type Querier
func (_mock *Querier) BeginTx(ctx context.Context, txOptions pgx.TxOptions) (pgx.Tx, error) {
	ret := _mock.Called(ctx, txOptions)

	if len(ret) == 0 {
		panic("no return value specified for BeginTx")
	}

	var r0 pgx.Tx
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, pgx.TxOptions) (pgx.Tx, error)); ok {
		return returnFunc(ctx, txOptions)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, pgx.TxOptions) pgx.Tx); ok {
		r0 = returnFunc(ctx, txOptions)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(pgx.Tx)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, pgx.TxOptions) error); ok {
		r1 = returnFunc(ctx, txOptions)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Querier_BeginTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BeginTx'
type Querier_BeginTx_Call struct {
	*mock.Call
}

// BeginTx is a helper method to define mock.On call
//   - ctx context.Context
//   - txOptions pgx.TxOptions
func (_e *Querier_Expecter) BeginTx(ctx interface{}, txOptions interface{}) *Querier_BeginTx_Call {
	return &Querier_BeginTx_Call{Call: _e.mock.On("BeginTx", ctx, txOptions)}
}

func (_c *Querier_BeginTx_Call) Run(run func(ctx context.Context, txOptions pgx.TxOptions)) *Querier_BeginTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 pgx.TxOptions
		if args[1] != nil {
			arg1 = args[1].(pgx.TxOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Querier_BeginTx_Call) Return(tx pgx.Tx, err error) *Querier_BeginTx_Call {
	_c.Call.Return(tx, err)
	return _c
}

func (_c *Querier_BeginTx_Call) RunAndReturn(run func(ctx context.Context, txOptions pgx.TxOptions) (pgx.Tx, error)) *Querier_BeginTx_Call {
	_c.Call.Return(run)
	return _c
}

// CanLobbyBeStarted provides a mock function for the type Querier
func (_mock *Querier) CanLobbyBeStarted(ctx context.Context, arg sqlc.CanLobbyBeStartedParams) (bool, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CanLobbyBeStarted")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.CanLobbyBeStartedParams) (bool, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.CanLobbyBeStartedParams) bool); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, sqlc.CanLobbyBeStartedParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Querier_CanLobbyBeStarted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CanLobbyBeStarted'
type Querier_CanLobbyBeStarted_Call struct {
	*mock.Call
}

// CanLobbyBeStarted is a helper method to define mock.On call
//   - ctx context.Context
//   - arg sqlc.CanLobbyBeStartedParams
func (_e *Querier_Expecter) CanLobbyBeStarted(ctx interface{}, arg interface{}) *Querier_CanLobbyBeStarted_Call {
	return &Querier_CanLobbyBeStarted_Call{Call: _e.mock.On("CanLobbyBeStarted", ctx, arg)}
}

func (_c *Querier_CanLobbyBeStarted_Call) Run(run func(ctx context.Context, arg sqlc.CanLobbyBeStartedParams)) *Querier_CanLobbyBeStarted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlc.CanLobbyBeStartedParams
		if args[1] != nil {
			arg1 = args[1].(sqlc.CanLobbyBeStartedParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Querier_CanLobbyBeStarted_Call) Return(b bool, err error) *Querier_CanLobbyBeStarted_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *Querier_CanLobbyBeStarted_Call) RunAndReturn(run func(ctx context.Context, arg sqlc.CanLobbyBeStartedParams) (bool, error)) *Querier_CanLobbyBeStarted_Call {
	_c.Call.Return(run)
	return _c
}

// CreateLobby provides a mock function for the type Querier
func (_mock *Querier) CreateLobby(ctx context.Context) (int64, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CreateLobby")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (int64, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) int64); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Querier_CreateLobby_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateLobby'
type Querier_CreateLobby_Call struct {
	*mock.Call
}

// CreateLobby is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Querier_Expecter) CreateLobby(ctx interface{}) *Querier_CreateLobby_Call {
	return &Querier_CreateLobby_Call{Call: _e.mock.On("CreateLobby", ctx)}
}

func (_c *Querier_CreateLobby_Call) Run(run func(ctx context.Context)) *Querier_CreateLobby_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Querier_CreateLobby_Call) Return(n int64, err error) *Querier_CreateLobby_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *Querier_CreateLobby_Call) RunAndReturn(run func(ctx context.Context) (int64, error)) *Querier_CreateLobby_Call {
	_c.Call.Return(run)
	return _c
}

// GetJoinableLobbies provides a mock function for the type Querier
func (_mock *Querier) GetJoinableLobbies(ctx context.Context, userID string) ([]sqlc.GetJoinableLobbiesRow, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetJoinableLobbies")
	}

	var r0 []sqlc.GetJoinableLobbiesRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]sqlc.GetJoinableLobbiesRow, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []sqlc.GetJoinableLobbiesRow); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]sqlc.GetJoinableLobbiesRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Querier_GetJoinableLobbies_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetJoinableLobbies'
type Querier_GetJoinableLobbies_Call struct {
	*mock.Call
}

// GetJoinableLobbies is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *Querier_Expecter) GetJoinableLobbies(ctx interface{}, userID interface{}) *Querier_GetJoinableLobbies_Call {
	return &Querier_GetJoinableLobbies_Call{Call: _e.mock.On("GetJoinableLobbies", ctx, userID)}
}

func (_c *Querier_GetJoinableLobbies_Call) Run(run func(ctx context.Context, userID string)) *Querier_GetJoinableLobbies_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Querier_GetJoinableLobbies_Call) Return(getJoinableLobbiesRows []sqlc.GetJoinableLobbiesRow, err error) *Querier_GetJoinableLobbies_Call {
	_c.Call.Return(getJoinableLobbiesRows, err)
	return _c
}

func (_c *Querier_GetJoinableLobbies_Call) RunAndReturn(run func(ctx context.Context, userID string) ([]sqlc.GetJoinableLobbiesRow, error)) *Querier_GetJoinableLobbies_Call {
	_c.Call.Return(run)
	return _c
}

// GetJoinedLobbies provides a mock function for the type Querier
func (_mock *Querier) GetJoinedLobbies(ctx context.Context, userID string) ([]sqlc.GetJoinedLobbiesRow, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetJoinedLobbies")
	}

	var r0 []sqlc.GetJoinedLobbiesRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]sqlc.GetJoinedLobbiesRow, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []sqlc.GetJoinedLobbiesRow); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]sqlc.GetJoinedLobbiesRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Querier_GetJoinedLobbies_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetJoinedLobbies'
type Querier_GetJoinedLobbies_Call struct {
	*mock.Call
}

// GetJoinedLobbies is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *Querier_Expecter) GetJoinedLobbies(ctx interface{}, userID interface{}) *Querier_GetJoinedLobbies_Call {
	return &Querier_GetJoinedLobbies_Call{Call: _e.mock.On("GetJoinedLobbies", ctx, userID)}
}

func (_c *Querier_GetJoinedLobbies_Call) Run(run func(ctx context.Context, userID string)) *Querier_GetJoinedLobbies_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Querier_GetJoinedLobbies_Call) Return(getJoinedLobbiesRows []sqlc.GetJoinedLobbiesRow, err error) *Querier_GetJoinedLobbies_Call {
	_c.Call.Return(getJoinedLobbiesRows, err)
	return _c
}

func (_c *Querier_GetJoinedLobbies_Call) RunAndReturn(run func(ctx context.Context, userID string) ([]sqlc.GetJoinedLobbiesRow, error)) *Querier_GetJoinedLobbies_Call {
	_c.Call.Return(run)
	return _c
}

// GetLobby provides a mock function for the type Querier
func (_mock *Querier) GetLobby(ctx context.Context, id int64) ([]sqlc.GetLobbyRow, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetLobby")
	}

	var r0 []sqlc.GetLobbyRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) ([]sqlc.GetLobbyRow, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) []sqlc.GetLobbyRow); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]sqlc.GetLobbyRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Querier_GetLobby_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLobby'
type Querier_GetLobby_Call struct {
	*mock.Call
}

// GetLobby is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *Querier_Expecter) GetLobby(ctx interface{}, id interface{}) *Querier_GetLobby_Call {
	return &Querier_GetLobby_Call{Call: _e.mock.On("GetLobby", ctx, id)}
}

func (_c *Querier_GetLobby_Call) Run(run func(ctx context.Context, id int64)) *Querier_GetLobby_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Querier_GetLobby_Call) Return(getLobbyRows []sqlc.GetLobbyRow, err error) *Querier_GetLobby_Call {
	_c.Call.Return(getLobbyRows, err)
	return _c
}

func (_c *Querier_GetLobby_Call) RunAndReturn(run func(ctx context.Context, id int64) ([]sqlc.GetLobbyRow, error)) *Querier_GetLobby_Call {
	_c.Call.Return(run)
	return _c
}

// GetLobbyPlayers provides a mock function for the type Querier
func (_mock *Querier) GetLobbyPlayers(ctx context.Context, id int64) ([]sqlc.GetLobbyPlayersRow, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetLobbyPlayers")
	}

	var r0 []sqlc.GetLobbyPlayersRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) ([]sqlc.GetLobbyPlayersRow, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) []sqlc.GetLobbyPlayersRow); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]sqlc.GetLobbyPlayersRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Querier_GetLobbyPlayers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLobbyPlayers'
type Querier_GetLobbyPlayers_Call struct {
	*mock.Call
}

// GetLobbyPlayers is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *Querier_Expecter) GetLobbyPlayers(ctx interface{}, id interface{}) *Querier_GetLobbyPlayers_Call {
	return &Querier_GetLobbyPlayers_Call{Call: _e.mock.On("GetLobbyPlayers", ctx, id)}
}

func (_c *Querier_GetLobbyPlayers_Call) Run(run func(ctx context.Context, id int64)) *Querier_GetLobbyPlayers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Querier_GetLobbyPlayers_Call) Return(getLobbyPlayersRows []sqlc.GetLobbyPlayersRow, err error) *Querier_GetLobbyPlayers_Call {
	_c.Call.Return(getLobbyPlayersRows, err)
	return _c
}

func (_c *Querier_GetLobbyPlayers_Call) RunAndReturn(run func(ctx context.Context, id int64) ([]sqlc.GetLobbyPlayersRow, error)) *Querier_GetLobbyPlayers_Call {
	_c.Call.Return(run)
	return _c
}

// GetOwnedLobbies provides a mock function for the type Querier
func (_mock *Querier) GetOwnedLobbies(ctx context.Context, userID string) ([]sqlc.GetOwnedLobbiesRow, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetOwnedLobbies")
	}

	var r0 []sqlc.GetOwnedLobbiesRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]sqlc.GetOwnedLobbiesRow, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []sqlc.GetOwnedLobbiesRow); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]sqlc.GetOwnedLobbiesRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Querier_GetOwnedLobbies_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOwnedLobbies'
type Querier_GetOwnedLobbies_Call struct {
	*mock.Call
}

// GetOwnedLobbies is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *Querier_Expecter) GetOwnedLobbies(ctx interface{}, userID interface{}) *Querier_GetOwnedLobbies_Call {
	return &Querier_GetOwnedLobbies_Call{Call: _e.mock.On("GetOwnedLobbies", ctx, userID)}
}

func (_c *Querier_GetOwnedLobbies_Call) Run(run func(ctx context.Context, userID string)) *Querier_GetOwnedLobbies_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Querier_GetOwnedLobbies_Call) Return(getOwnedLobbiesRows []sqlc.GetOwnedLobbiesRow, err error) *Querier_GetOwnedLobbies_Call {
	_c.Call.Return(getOwnedLobbiesRows, err)
	return _c
}

func (_c *Querier_GetOwnedLobbies_Call) RunAndReturn(run func(ctx context.Context, userID string) ([]sqlc.GetOwnedLobbiesRow, error)) *Querier_GetOwnedLobbies_Call {
	_c.Call.Return(run)
	return _c
}

// InsertParticipant provides a mock function for the type Querier
func (_mock *Querier) InsertParticipant(ctx context.Context, arg sqlc.InsertParticipantParams) (int64, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for InsertParticipant")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.InsertParticipantParams) (int64, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.InsertParticipantParams) int64); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, sqlc.InsertParticipantParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Querier_InsertParticipant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertParticipant'
type Querier_InsertParticipant_Call struct {
	*mock.Call
}

// InsertParticipant is a helper method to define mock.On call
//   - ctx context.Context
//   - arg sqlc.InsertParticipantParams
func (_e *Querier_Expecter) InsertParticipant(ctx interface{}, arg interface{}) *Querier_InsertParticipant_Call {
	return &Querier_InsertParticipant_Call{Call: _e.mock.On("InsertParticipant", ctx, arg)}
}

func (_c *Querier_InsertParticipant_Call) Run(run func(ctx context.Context, arg sqlc.InsertParticipantParams)) *Querier_InsertParticipant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlc.InsertParticipantParams
		if args[1] != nil {
			arg1 = args[1].(sqlc.InsertParticipantParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Querier_InsertParticipant_Call) Return(n int64, err error) *Querier_InsertParticipant_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *Querier_InsertParticipant_Call) RunAndReturn(run func(ctx context.Context, arg sqlc.InsertParticipantParams) (int64, error)) *Querier_InsertParticipant_Call {
	_c.Call.Return(run)
	return _c
}

// MarkLobbyAsStarted provides a mock function for the type Querier
func (_mock *Querier) MarkLobbyAsStarted(ctx context.Context, arg sqlc.MarkLobbyAsStartedParams) error {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for MarkLobbyAsStarted")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.MarkLobbyAsStartedParams) error); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Querier_MarkLobbyAsStarted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkLobbyAsStarted'
type Querier_MarkLobbyAsStarted_Call struct {
	*mock.Call
}

// MarkLobbyAsStarted is a helper method to define mock.On call
//   - ctx context.Context
//   - arg sqlc.MarkLobbyAsStartedParams
func (_e *Querier_Expecter) MarkLobbyAsStarted(ctx interface{}, arg interface{}) *Querier_MarkLobbyAsStarted_Call {
	return &Querier_MarkLobbyAsStarted_Call{Call: _e.mock.On("MarkLobbyAsStarted", ctx, arg)}
}

func (_c *Querier_MarkLobbyAsStarted_Call) Run(run func(ctx context.Context, arg sqlc.MarkLobbyAsStartedParams)) *Querier_MarkLobbyAsStarted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlc.MarkLobbyAsStartedParams
		if args[1] != nil {
			arg1 = args[1].(sqlc.MarkLobbyAsStartedParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Querier_MarkLobbyAsStarted_Call) Return(err error) *Querier_MarkLobbyAsStarted_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Querier_MarkLobbyAsStarted_Call) RunAndReturn(run func(ctx context.Context, arg sqlc.MarkLobbyAsStartedParams) error) *Querier_MarkLobbyAsStarted_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateLobbyOwner provides a mock function for the type Querier
func (_mock *Querier) UpdateLobbyOwner(ctx context.Context, arg sqlc.UpdateLobbyOwnerParams) error {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateLobbyOwner")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.UpdateLobbyOwnerParams) error); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Querier_UpdateLobbyOwner_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateLobbyOwner'
type Querier_UpdateLobbyOwner_Call struct {
	*mock.Call
}

// UpdateLobbyOwner is a helper method to define mock.On call
//   - ctx context.Context
//   - arg sqlc.UpdateLobbyOwnerParams
func (_e *Querier_Expecter) UpdateLobbyOwner(ctx interface{}, arg interface{}) *Querier_UpdateLobbyOwner_Call {
	return &Querier_UpdateLobbyOwner_Call{Call: _e.mock.On("UpdateLobbyOwner", ctx, arg)}
}

func (_c *Querier_UpdateLobbyOwner_Call) Run(run func(ctx context.Context, arg sqlc.UpdateLobbyOwnerParams)) *Querier_UpdateLobbyOwner_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlc.UpdateLobbyOwnerParams
		if args[1] != nil {
			arg1 = args[1].(sqlc.UpdateLobbyOwnerParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Querier_UpdateLobbyOwner_Call) Return(err error) *Querier_UpdateLobbyOwner_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Querier_UpdateLobbyOwner_Call) RunAndReturn(run func(ctx context.Context, arg sqlc.UpdateLobbyOwnerParams) error) *Querier_UpdateLobbyOwner_Call {
	_c.Call.Return(run)
	return _c
}

// WithTx provides a mock function for the type Querier
func (_mock *Querier) WithTx(tx pgx.Tx) db.Querier {
	ret := _mock.Called(tx)

	if len(ret) == 0 {
		panic("no return value specified for WithTx")
	}

	var r0 db.Querier
	if returnFunc, ok := ret.Get(0).(func(pgx.Tx) db.Querier); ok {
		r0 = returnFunc(tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(db.Querier)
		}
	}
	return r0
}

// Querier_WithTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithTx'
type Querier_WithTx_Call struct {
	*mock.Call
}

// WithTx is a helper method to define mock.On call
//   - tx pgx.Tx
func (_e *Querier_Expecter) WithTx(tx interface{}) *Querier_WithTx_Call {
	return &Querier_WithTx_Call{Call: _e.mock.On("WithTx", tx)}
}

func (_c *Querier_WithTx_Call) Run(run func(tx pgx.Tx)) *Querier_WithTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 pgx.Tx
		if args[0] != nil {
			arg0 = args[0].(pgx.Tx)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Querier_WithTx_Call) Return(querier db.Querier) *Querier_WithTx_Call {
	_c.Call.Return(querier)
	return _c
}

func (_c *Querier_WithTx_Call) RunAndReturn(run func(tx pgx.Tx) db.Querier) *Querier_WithTx_Call {
	_c.Call.Return(run)
	return _c
}
