// Code generated by mockery v2.46.3. DO NOT EDIT.

package testonly

import (
	ctx "github.com/go-risk-it/go-risk-it/internal/ctx"
	mock "github.com/stretchr/testify/mock"
)

// Controller is an autogenerated mock type for the Controller type
type Controller struct {
	mock.Mock
}

type Controller_Expecter struct {
	mock *mock.Mock
}

func (_m *Controller) EXPECT() *Controller_Expecter {
	return &Controller_Expecter{mock: &_m.Mock}
}

// ResetState provides a mock function with given fields: _a0
func (_m *Controller) ResetState(_a0 ctx.LogContext) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for ResetState")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(ctx.LogContext) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Controller_ResetState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResetState'
type Controller_ResetState_Call struct {
	*mock.Call
}

// ResetState is a helper method to define mock.On call
//   - _a0 ctx.LogContext
func (_e *Controller_Expecter) ResetState(_a0 interface{}) *Controller_ResetState_Call {
	return &Controller_ResetState_Call{Call: _e.mock.On("ResetState", _a0)}
}

func (_c *Controller_ResetState_Call) Run(run func(_a0 ctx.LogContext)) *Controller_ResetState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(ctx.LogContext))
	})
	return _c
}

func (_c *Controller_ResetState_Call) Return(_a0 error) *Controller_ResetState_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Controller_ResetState_Call) RunAndReturn(run func(ctx.LogContext) error) *Controller_ResetState_Call {
	_c.Call.Return(run)
	return _c
}

// NewController creates a new instance of Controller. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewController(t interface {
	mock.TestingT
	Cleanup(func())
}) *Controller {
	mock := &Controller{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
