// Code generated by mockery v2.42.1. DO NOT EDIT.

package testonly

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// Handler is an autogenerated mock type for the Handler type
type Handler struct {
	mock.Mock
}

type Handler_Expecter struct {
	mock *mock.Mock
}

func (_m *Handler) EXPECT() *Handler_Expecter {
	return &Handler_Expecter{mock: &_m.Mock}
}

// OnReset provides a mock function with given fields: w, r
func (_m *Handler) OnReset(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// Handler_OnReset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnReset'
type Handler_OnReset_Call struct {
	*mock.Call
}

// OnReset is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *Handler_Expecter) OnReset(w interface{}, r interface{}) *Handler_OnReset_Call {
	return &Handler_OnReset_Call{Call: _e.mock.On("OnReset", w, r)}
}

func (_c *Handler_OnReset_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *Handler_OnReset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *Handler_OnReset_Call) Return() *Handler_OnReset_Call {
	_c.Call.Return()
	return _c
}

func (_c *Handler_OnReset_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *Handler_OnReset_Call {
	_c.Call.Return(run)
	return _c
}

// NewHandler creates a new instance of Handler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *Handler {
	mock := &Handler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
