// Code generated by mockery v2.43.1. DO NOT EDIT.

package testonly

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// ResetHandler is an autogenerated mock type for the ResetHandler type
type ResetHandler struct {
	mock.Mock
}

type ResetHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *ResetHandler) EXPECT() *ResetHandler_Expecter {
	return &ResetHandler_Expecter{mock: &_m.Mock}
}

// Pattern provides a mock function with given fields:
func (_m *ResetHandler) Pattern() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Pattern")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// ResetHandler_Pattern_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Pattern'
type ResetHandler_Pattern_Call struct {
	*mock.Call
}

// Pattern is a helper method to define mock.On call
func (_e *ResetHandler_Expecter) Pattern() *ResetHandler_Pattern_Call {
	return &ResetHandler_Pattern_Call{Call: _e.mock.On("Pattern")}
}

func (_c *ResetHandler_Pattern_Call) Run(run func()) *ResetHandler_Pattern_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ResetHandler_Pattern_Call) Return(_a0 string) *ResetHandler_Pattern_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ResetHandler_Pattern_Call) RunAndReturn(run func() string) *ResetHandler_Pattern_Call {
	_c.Call.Return(run)
	return _c
}

// ServeHTTP provides a mock function with given fields: w, r
func (_m *ResetHandler) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// ResetHandler_ServeHTTP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ServeHTTP'
type ResetHandler_ServeHTTP_Call struct {
	*mock.Call
}

// ServeHTTP is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *ResetHandler_Expecter) ServeHTTP(w interface{}, r interface{}) *ResetHandler_ServeHTTP_Call {
	return &ResetHandler_ServeHTTP_Call{Call: _e.mock.On("ServeHTTP", w, r)}
}

func (_c *ResetHandler_ServeHTTP_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *ResetHandler_ServeHTTP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *ResetHandler_ServeHTTP_Call) Return() *ResetHandler_ServeHTTP_Call {
	_c.Call.Return()
	return _c
}

func (_c *ResetHandler_ServeHTTP_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *ResetHandler_ServeHTTP_Call {
	_c.Call.Return(run)
	return _c
}

// NewResetHandler creates a new instance of ResetHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewResetHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *ResetHandler {
	mock := &ResetHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
