// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package board

import (
	"github.com/go-risk-it/go-risk-it/internal/logic/game/board"
	mock "github.com/stretchr/testify/mock"
)

// NewContinents creates a new instance of Continents. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewContinents(t interface {
	mock.TestingT
	Cleanup(func())
},
) *Continents {
	mock := &Continents{}
	mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Continents is an autogenerated mock type for the Continents type.
type Continents struct {
	mock.Mock
}

type Continents_Expecter struct {
	mock *mock.Mock
}

func (_m *Continents) EXPECT() *Continents_Expecter {
	return &Continents_Expecter{mock: &_m.Mock}
}

// All provides a mock function for the type Continents.
func (_mock *Continents) All() []*board.Continent {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for All")
	}

	var r0 []*board.Continent
	if returnFunc, ok := ret.Get(0).(func() []*board.Continent); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*board.Continent)
		}
	}

	return r0
}

// Continents_All_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'All'.
type Continents_All_Call struct {
	*mock.Call
}

// All is a helper method to define mock.On call.
func (_e *Continents_Expecter) All() *Continents_All_Call {
	return &Continents_All_Call{Call: _e.mock.On("All")}
}

func (_c *Continents_All_Call) Run(run func()) *Continents_All_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})

	return _c
}

func (_c *Continents_All_Call) Return(continents []*board.Continent) *Continents_All_Call {
	_c.Call.Return(continents)

	return _c
}

func (_c *Continents_All_Call) RunAndReturn(run func() []*board.Continent) *Continents_All_Call {
	_c.Call.Return(run)

	return _c
}

// GetContinentsControlledBy provides a mock function for the type Continents.
func (_mock *Continents) GetContinentsControlledBy(regions []string) []*board.Continent {
	ret := _mock.Called(regions)

	if len(ret) == 0 {
		panic("no return value specified for GetContinentsControlledBy")
	}

	var r0 []*board.Continent
	if returnFunc, ok := ret.Get(0).(func([]string) []*board.Continent); ok {
		r0 = returnFunc(regions)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*board.Continent)
		}
	}

	return r0
}

// Continents_GetContinentsControlledBy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetContinentsControlledBy'.
type Continents_GetContinentsControlledBy_Call struct {
	*mock.Call
}

// GetContinentsControlledBy is a helper method to define mock.On call
//   - regions []string
func (_e *Continents_Expecter) GetContinentsControlledBy(regions any) *Continents_GetContinentsControlledBy_Call {
	return &Continents_GetContinentsControlledBy_Call{Call: _e.mock.On("GetContinentsControlledBy", regions)}
}

func (_c *Continents_GetContinentsControlledBy_Call) Run(run func(regions []string)) *Continents_GetContinentsControlledBy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []string
		if args[0] != nil {
			arg0 = args[0].([]string)
		}
		run(
			arg0,
		)
	})

	return _c
}

func (_c *Continents_GetContinentsControlledBy_Call) Return(continents []*board.Continent) *Continents_GetContinentsControlledBy_Call {
	_c.Call.Return(continents)

	return _c
}

func (_c *Continents_GetContinentsControlledBy_Call) RunAndReturn(run func(regions []string) []*board.Continent) *Continents_GetContinentsControlledBy_Call {
	_c.Call.Return(run)

	return _c
}
