// Code generated by mockery v2.43.1. DO NOT EDIT.

package board

import (
	board "github.com/go-risk-it/go-risk-it/internal/logic/game/board"
	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

type Service_Expecter struct {
	mock *mock.Mock
}

func (_m *Service) EXPECT() *Service_Expecter {
	return &Service_Expecter{mock: &_m.Mock}
}

// GetBoard provides a mock function with given fields:
func (_m *Service) GetBoard() (*board.Board, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetBoard")
	}

	var r0 *board.Board
	var r1 error
	if rf, ok := ret.Get(0).(func() (*board.Board, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *board.Board); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*board.Board)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_GetBoard_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBoard'
type Service_GetBoard_Call struct {
	*mock.Call
}

// GetBoard is a helper method to define mock.On call
func (_e *Service_Expecter) GetBoard() *Service_GetBoard_Call {
	return &Service_GetBoard_Call{Call: _e.mock.On("GetBoard")}
}

func (_c *Service_GetBoard_Call) Run(run func()) *Service_GetBoard_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Service_GetBoard_Call) Return(_a0 *board.Board, _a1 error) *Service_GetBoard_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_GetBoard_Call) RunAndReturn(run func() (*board.Board, error)) *Service_GetBoard_Call {
	_c.Call.Return(run)
	return _c
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
