// Code generated by mockery v2.40.1. DO NOT EDIT.

package board

import (
	mock "github.com/stretchr/testify/mock"
	request "github.com/tomfran/go-risk-it/internal/api/game/message/request"
	response "github.com/tomfran/go-risk-it/internal/api/game/message/response"
)

// Controller is an autogenerated mock type for the Controller type
type Controller struct {
	mock.Mock
}

type Controller_Expecter struct {
	mock *mock.Mock
}

func (_m *Controller) EXPECT() *Controller_Expecter {
	return &Controller_Expecter{mock: &_m.Mock}
}

// GetBoardState provides a mock function with given fields: _a0
func (_m *Controller) GetBoardState(_a0 request.BoardStateRequest) (response.BoardStateResponse, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for GetBoardState")
	}

	var r0 response.BoardStateResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(request.BoardStateRequest) (response.BoardStateResponse, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(request.BoardStateRequest) response.BoardStateResponse); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(response.BoardStateResponse)
	}

	if rf, ok := ret.Get(1).(func(request.BoardStateRequest) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Controller_GetBoardState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBoardState'
type Controller_GetBoardState_Call struct {
	*mock.Call
}

// GetBoardState is a helper method to define mock.On call
//   - _a0 request.BoardStateRequest
func (_e *Controller_Expecter) GetBoardState(_a0 interface{}) *Controller_GetBoardState_Call {
	return &Controller_GetBoardState_Call{Call: _e.mock.On("GetBoardState", _a0)}
}

func (_c *Controller_GetBoardState_Call) Run(run func(_a0 request.BoardStateRequest)) *Controller_GetBoardState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(request.BoardStateRequest))
	})
	return _c
}

func (_c *Controller_GetBoardState_Call) Return(_a0 response.BoardStateResponse, _a1 error) *Controller_GetBoardState_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Controller_GetBoardState_Call) RunAndReturn(run func(request.BoardStateRequest) (response.BoardStateResponse, error)) *Controller_GetBoardState_Call {
	_c.Call.Return(run)
	return _c
}

// NewController creates a new instance of Controller. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewController(t interface {
	mock.TestingT
	Cleanup(func())
}) *Controller {
	mock := &Controller{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
