// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package management

import (
	"github.com/go-risk-it/go-risk-it/internal/kernel/ctx"
	ctx0 "github.com/go-risk-it/go-risk-it/internal/lobby/ctx"
	"github.com/go-risk-it/go-risk-it/internal/lobby/internal/data/db"
	"github.com/go-risk-it/go-risk-it/internal/lobby/internal/logic/management"
	mock "github.com/stretchr/testify/mock"
)

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

type Service_Expecter struct {
	mock *mock.Mock
}

func (_m *Service) EXPECT() *Service_Expecter {
	return &Service_Expecter{mock: &_m.Mock}
}

// GetUserLobbies provides a mock function for the type Service
func (_mock *Service) GetUserLobbies(ctx1 ctx.UserContext) (*management.UserLobbies, error) {
	ret := _mock.Called(ctx1)

	if len(ret) == 0 {
		panic("no return value specified for GetUserLobbies")
	}

	var r0 *management.UserLobbies
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(ctx.UserContext) (*management.UserLobbies, error)); ok {
		return returnFunc(ctx1)
	}
	if returnFunc, ok := ret.Get(0).(func(ctx.UserContext) *management.UserLobbies); ok {
		r0 = returnFunc(ctx1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*management.UserLobbies)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(ctx.UserContext) error); ok {
		r1 = returnFunc(ctx1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Service_GetUserLobbies_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserLobbies'
type Service_GetUserLobbies_Call struct {
	*mock.Call
}

// GetUserLobbies is a helper method to define mock.On call
//   - ctx1 ctx.UserContext
func (_e *Service_Expecter) GetUserLobbies(ctx1 interface{}) *Service_GetUserLobbies_Call {
	return &Service_GetUserLobbies_Call{Call: _e.mock.On("GetUserLobbies", ctx1)}
}

func (_c *Service_GetUserLobbies_Call) Run(run func(ctx1 ctx.UserContext)) *Service_GetUserLobbies_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 ctx.UserContext
		if args[0] != nil {
			arg0 = args[0].(ctx.UserContext)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Service_GetUserLobbies_Call) Return(userLobbies *management.UserLobbies, err error) *Service_GetUserLobbies_Call {
	_c.Call.Return(userLobbies, err)
	return _c
}

func (_c *Service_GetUserLobbies_Call) RunAndReturn(run func(ctx1 ctx.UserContext) (*management.UserLobbies, error)) *Service_GetUserLobbies_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserLobbiesWithQuerier provides a mock function for the type Service
func (_mock *Service) GetUserLobbiesWithQuerier(ctx1 ctx.UserContext, querier db.Querier) (*management.UserLobbies, error) {
	ret := _mock.Called(ctx1, querier)

	if len(ret) == 0 {
		panic("no return value specified for GetUserLobbiesWithQuerier")
	}

	var r0 *management.UserLobbies
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(ctx.UserContext, db.Querier) (*management.UserLobbies, error)); ok {
		return returnFunc(ctx1, querier)
	}
	if returnFunc, ok := ret.Get(0).(func(ctx.UserContext, db.Querier) *management.UserLobbies); ok {
		r0 = returnFunc(ctx1, querier)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*management.UserLobbies)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(ctx.UserContext, db.Querier) error); ok {
		r1 = returnFunc(ctx1, querier)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Service_GetUserLobbiesWithQuerier_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserLobbiesWithQuerier'
type Service_GetUserLobbiesWithQuerier_Call struct {
	*mock.Call
}

// GetUserLobbiesWithQuerier is a helper method to define mock.On call
//   - ctx1 ctx.UserContext
//   - querier db.Querier
func (_e *Service_Expecter) GetUserLobbiesWithQuerier(ctx1 interface{}, querier interface{}) *Service_GetUserLobbiesWithQuerier_Call {
	return &Service_GetUserLobbiesWithQuerier_Call{Call: _e.mock.On("GetUserLobbiesWithQuerier", ctx1, querier)}
}

func (_c *Service_GetUserLobbiesWithQuerier_Call) Run(run func(ctx1 ctx.UserContext, querier db.Querier)) *Service_GetUserLobbiesWithQuerier_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 ctx.UserContext
		if args[0] != nil {
			arg0 = args[0].(ctx.UserContext)
		}
		var arg1 db.Querier
		if args[1] != nil {
			arg1 = args[1].(db.Querier)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Service_GetUserLobbiesWithQuerier_Call) Return(userLobbies *management.UserLobbies, err error) *Service_GetUserLobbiesWithQuerier_Call {
	_c.Call.Return(userLobbies, err)
	return _c
}

func (_c *Service_GetUserLobbiesWithQuerier_Call) RunAndReturn(run func(ctx1 ctx.UserContext, querier db.Querier) (*management.UserLobbies, error)) *Service_GetUserLobbiesWithQuerier_Call {
	_c.Call.Return(run)
	return _c
}

// JoinLobby provides a mock function for the type Service
func (_mock *Service) JoinLobby(ctx1 ctx0.LobbyContext, name string) error {
	ret := _mock.Called(ctx1, name)

	if len(ret) == 0 {
		panic("no return value specified for JoinLobby")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(ctx0.LobbyContext, string) error); ok {
		r0 = returnFunc(ctx1, name)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Service_JoinLobby_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'JoinLobby'
type Service_JoinLobby_Call struct {
	*mock.Call
}

// JoinLobby is a helper method to define mock.On call
//   - ctx1 ctx0.LobbyContext
//   - name string
func (_e *Service_Expecter) JoinLobby(ctx1 interface{}, name interface{}) *Service_JoinLobby_Call {
	return &Service_JoinLobby_Call{Call: _e.mock.On("JoinLobby", ctx1, name)}
}

func (_c *Service_JoinLobby_Call) Run(run func(ctx1 ctx0.LobbyContext, name string)) *Service_JoinLobby_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 ctx0.LobbyContext
		if args[0] != nil {
			arg0 = args[0].(ctx0.LobbyContext)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Service_JoinLobby_Call) Return(err error) *Service_JoinLobby_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Service_JoinLobby_Call) RunAndReturn(run func(ctx1 ctx0.LobbyContext, name string) error) *Service_JoinLobby_Call {
	_c.Call.Return(run)
	return _c
}

// JoinLobbyWithQuerier provides a mock function for the type Service
func (_mock *Service) JoinLobbyWithQuerier(ctx1 ctx0.LobbyContext, querier db.Querier, name string) error {
	ret := _mock.Called(ctx1, querier, name)

	if len(ret) == 0 {
		panic("no return value specified for JoinLobbyWithQuerier")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(ctx0.LobbyContext, db.Querier, string) error); ok {
		r0 = returnFunc(ctx1, querier, name)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Service_JoinLobbyWithQuerier_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'JoinLobbyWithQuerier'
type Service_JoinLobbyWithQuerier_Call struct {
	*mock.Call
}

// JoinLobbyWithQuerier is a helper method to define mock.On call
//   - ctx1 ctx0.LobbyContext
//   - querier db.Querier
//   - name string
func (_e *Service_Expecter) JoinLobbyWithQuerier(ctx1 interface{}, querier interface{}, name interface{}) *Service_JoinLobbyWithQuerier_Call {
	return &Service_JoinLobbyWithQuerier_Call{Call: _e.mock.On("JoinLobbyWithQuerier", ctx1, querier, name)}
}

func (_c *Service_JoinLobbyWithQuerier_Call) Run(run func(ctx1 ctx0.LobbyContext, querier db.Querier, name string)) *Service_JoinLobbyWithQuerier_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 ctx0.LobbyContext
		if args[0] != nil {
			arg0 = args[0].(ctx0.LobbyContext)
		}
		var arg1 db.Querier
		if args[1] != nil {
			arg1 = args[1].(db.Querier)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Service_JoinLobbyWithQuerier_Call) Return(err error) *Service_JoinLobbyWithQuerier_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Service_JoinLobbyWithQuerier_Call) RunAndReturn(run func(ctx1 ctx0.LobbyContext, querier db.Querier, name string) error) *Service_JoinLobbyWithQuerier_Call {
	_c.Call.Return(run)
	return _c
}
