// Code generated by mockery v2.43.1. DO NOT EDIT.

package dice

import mock "github.com/stretchr/testify/mock"

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

type Service_Expecter struct {
	mock *mock.Mock
}

func (_m *Service) EXPECT() *Service_Expecter {
	return &Service_Expecter{mock: &_m.Mock}
}

// Roll provides a mock function with given fields: n
func (_m *Service) Roll(n int) []int {
	ret := _m.Called(n)

	if len(ret) == 0 {
		panic("no return value specified for Roll")
	}

	var r0 []int
	if rf, ok := ret.Get(0).(func(int) []int); ok {
		r0 = rf(n)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]int)
		}
	}

	return r0
}

// Service_Roll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Roll'
type Service_Roll_Call struct {
	*mock.Call
}

// Roll is a helper method to define mock.On call
//   - n int
func (_e *Service_Expecter) Roll(n interface{}) *Service_Roll_Call {
	return &Service_Roll_Call{Call: _e.mock.On("Roll", n)}
}

func (_c *Service_Roll_Call) Run(run func(n int)) *Service_Roll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *Service_Roll_Call) Return(_a0 []int) *Service_Roll_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Service_Roll_Call) RunAndReturn(run func(int) []int) *Service_Roll_Call {
	_c.Call.Return(run)
	return _c
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
