// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package bus

import (
	"log/slog"

	mock "github.com/stretchr/testify/mock"
)

// NewScopedEvent creates a new instance of ScopedEvent. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewScopedEvent(t interface {
	mock.TestingT
	Cleanup(func())
}) *ScopedEvent {
	mock := &ScopedEvent{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ScopedEvent is an autogenerated mock type for the ScopedEvent type
type ScopedEvent struct {
	mock.Mock
}

type ScopedEvent_Expecter struct {
	mock *mock.Mock
}

func (_m *ScopedEvent) EXPECT() *ScopedEvent_Expecter {
	return &ScopedEvent_Expecter{mock: &_m.Mock}
}

// ScopeAttrs provides a mock function for the type ScopedEvent
func (_mock *ScopedEvent) ScopeAttrs() []slog.Attr {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ScopeAttrs")
	}

	var r0 []slog.Attr
	if returnFunc, ok := ret.Get(0).(func() []slog.Attr); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]slog.Attr)
		}
	}
	return r0
}

// ScopedEvent_ScopeAttrs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ScopeAttrs'
type ScopedEvent_ScopeAttrs_Call struct {
	*mock.Call
}

// ScopeAttrs is a helper method to define mock.On call
func (_e *ScopedEvent_Expecter) ScopeAttrs() *ScopedEvent_ScopeAttrs_Call {
	return &ScopedEvent_ScopeAttrs_Call{Call: _e.mock.On("ScopeAttrs")}
}

func (_c *ScopedEvent_ScopeAttrs_Call) Run(run func()) *ScopedEvent_ScopeAttrs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ScopedEvent_ScopeAttrs_Call) Return(attrs []slog.Attr) *ScopedEvent_ScopeAttrs_Call {
	_c.Call.Return(attrs)
	return _c
}

func (_c *ScopedEvent_ScopeAttrs_Call) RunAndReturn(run func() []slog.Attr) *ScopedEvent_ScopeAttrs_Call {
	_c.Call.Return(run)
	return _c
}
