// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service

import (
	"github.com/go-risk-it/go-risk-it/internal/ctx"
	"github.com/go-risk-it/go-risk-it/internal/data/game/db"
	"github.com/go-risk-it/go-risk-it/internal/data/game/sqlc"
	mock "github.com/stretchr/testify/mock"
)

// NewAdvancer creates a new instance of Advancer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAdvancer[R any](t interface {
	mock.TestingT
	Cleanup(func())
}) *Advancer[R] {
	mock := &Advancer[R]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Advancer is an autogenerated mock type for the Advancer type
type Advancer[R any] struct {
	mock.Mock
}

type Advancer_Expecter[R any] struct {
	mock *mock.Mock
}

func (_m *Advancer[R]) EXPECT() *Advancer_Expecter[R] {
	return &Advancer_Expecter[R]{mock: &_m.Mock}
}

// Advance provides a mock function for the type Advancer
func (_mock *Advancer[R]) Advance(ctx1 ctx.GameContext, querier db.Querier, targetPhase sqlc.GamePhaseType, performResult R) error {
	ret := _mock.Called(ctx1, querier, targetPhase, performResult)

	if len(ret) == 0 {
		panic("no return value specified for Advance")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(ctx.GameContext, db.Querier, sqlc.GamePhaseType, R) error); ok {
		r0 = returnFunc(ctx1, querier, targetPhase, performResult)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Advancer_Advance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Advance'
type Advancer_Advance_Call[R any] struct {
	*mock.Call
}

// Advance is a helper method to define mock.On call
//   - ctx1 ctx.GameContext
//   - querier db.Querier
//   - targetPhase sqlc.GamePhaseType
//   - performResult R
func (_e *Advancer_Expecter[R]) Advance(ctx1 interface{}, querier interface{}, targetPhase interface{}, performResult interface{}) *Advancer_Advance_Call[R] {
	return &Advancer_Advance_Call[R]{Call: _e.mock.On("Advance", ctx1, querier, targetPhase, performResult)}
}

func (_c *Advancer_Advance_Call[R]) Run(run func(ctx1 ctx.GameContext, querier db.Querier, targetPhase sqlc.GamePhaseType, performResult R)) *Advancer_Advance_Call[R] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 ctx.GameContext
		if args[0] != nil {
			arg0 = args[0].(ctx.GameContext)
		}
		var arg1 db.Querier
		if args[1] != nil {
			arg1 = args[1].(db.Querier)
		}
		var arg2 sqlc.GamePhaseType
		if args[2] != nil {
			arg2 = args[2].(sqlc.GamePhaseType)
		}
		var arg3 R
		if args[3] != nil {
			arg3 = args[3].(R)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *Advancer_Advance_Call[R]) Return(err error) *Advancer_Advance_Call[R] {
	_c.Call.Return(err)
	return _c
}

func (_c *Advancer_Advance_Call[R]) RunAndReturn(run func(ctx1 ctx.GameContext, querier db.Querier, targetPhase sqlc.GamePhaseType, performResult R) error) *Advancer_Advance_Call[R] {
	_c.Call.Return(run)
	return _c
}
