// Code generated by mockery v2.44.1. DO NOT EDIT.

package service

import (
	ctx "github.com/go-risk-it/go-risk-it/internal/ctx"
	db "github.com/go-risk-it/go-risk-it/internal/data/db"

	mock "github.com/stretchr/testify/mock"

	sqlc "github.com/go-risk-it/go-risk-it/internal/data/sqlc"
)

// Advancer is an autogenerated mock type for the Advancer type
type Advancer[T interface{}] struct {
	mock.Mock
}

type Advancer_Expecter[T interface{}] struct {
	mock *mock.Mock
}

func (_m *Advancer[T]) EXPECT() *Advancer_Expecter[T] {
	return &Advancer_Expecter[T]{mock: &_m.Mock}
}

// AdvanceQ provides a mock function with given fields: _a0, querier, targetPhase, move
func (_m *Advancer[T]) AdvanceQ(_a0 ctx.MoveContext, querier db.Querier, targetPhase sqlc.PhaseType, move T) error {
	ret := _m.Called(_a0, querier, targetPhase, move)

	if len(ret) == 0 {
		panic("no return value specified for AdvanceQ")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(ctx.MoveContext, db.Querier, sqlc.PhaseType, T) error); ok {
		r0 = rf(_a0, querier, targetPhase, move)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Advancer_AdvanceQ_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AdvanceQ'
type Advancer_AdvanceQ_Call[T interface{}] struct {
	*mock.Call
}

// AdvanceQ is a helper method to define mock.On call
//   - _a0 ctx.MoveContext
//   - querier db.Querier
//   - targetPhase sqlc.PhaseType
//   - move T
func (_e *Advancer_Expecter[T]) AdvanceQ(_a0 interface{}, querier interface{}, targetPhase interface{}, move interface{}) *Advancer_AdvanceQ_Call[T] {
	return &Advancer_AdvanceQ_Call[T]{Call: _e.mock.On("AdvanceQ", _a0, querier, targetPhase, move)}
}

func (_c *Advancer_AdvanceQ_Call[T]) Run(run func(_a0 ctx.MoveContext, querier db.Querier, targetPhase sqlc.PhaseType, move T)) *Advancer_AdvanceQ_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(ctx.MoveContext), args[1].(db.Querier), args[2].(sqlc.PhaseType), args[3].(T))
	})
	return _c
}

func (_c *Advancer_AdvanceQ_Call[T]) Return(_a0 error) *Advancer_AdvanceQ_Call[T] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Advancer_AdvanceQ_Call[T]) RunAndReturn(run func(ctx.MoveContext, db.Querier, sqlc.PhaseType, T) error) *Advancer_AdvanceQ_Call[T] {
	_c.Call.Return(run)
	return _c
}

// NewAdvancer creates a new instance of Advancer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAdvancer[T interface{}](t interface {
	mock.TestingT
	Cleanup(func())
}) *Advancer[T] {
	mock := &Advancer[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
