// Code generated by mockery v2.53.6. DO NOT EDIT.

package service

import (
	ctx "github.com/go-risk-it/go-risk-it/internal/ctx"
	db "github.com/go-risk-it/go-risk-it/internal/data/game/db"

	mock "github.com/stretchr/testify/mock"

	sqlc "github.com/go-risk-it/go-risk-it/internal/data/game/sqlc"
)

// Service is an autogenerated mock type for the Service type
type Service[T any] struct {
	mock.Mock
}

type Service_Expecter[T any] struct {
	mock *mock.Mock
}

func (_m *Service[T]) EXPECT() *Service_Expecter[T] {
	return &Service_Expecter[T]{mock: &_m.Mock}
}

// Advance provides a mock function with given fields: _a0, querier, targetPhase, performResult
func (_m *Service[T]) Advance(_a0 ctx.GameContext, querier db.Querier, targetPhase sqlc.GamePhaseType, performResult any) error {
	ret := _m.Called(_a0, querier, targetPhase, performResult)

	if len(ret) == 0 {
		panic("no return value specified for Advance")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(ctx.GameContext, db.Querier, sqlc.GamePhaseType, any) error); ok {
		r0 = rf(_a0, querier, targetPhase, performResult)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Service_Advance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Advance'
type Service_Advance_Call[T any] struct {
	*mock.Call
}

// Advance is a helper method to define mock.On call
//   - _a0 ctx.GameContext
//   - querier db.Querier
//   - targetPhase sqlc.GamePhaseType
//   - performResult any
func (_e *Service_Expecter[T]) Advance(_a0 interface{}, querier interface{}, targetPhase interface{}, performResult interface{}) *Service_Advance_Call[T] {
	return &Service_Advance_Call[T]{Call: _e.mock.On("Advance", _a0, querier, targetPhase, performResult)}
}

func (_c *Service_Advance_Call[T]) Run(run func(_a0 ctx.GameContext, querier db.Querier, targetPhase sqlc.GamePhaseType, performResult any)) *Service_Advance_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(ctx.GameContext), args[1].(db.Querier), args[2].(sqlc.GamePhaseType), args[3].(any))
	})
	return _c
}

func (_c *Service_Advance_Call[T]) Return(_a0 error) *Service_Advance_Call[T] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Service_Advance_Call[T]) RunAndReturn(run func(ctx.GameContext, db.Querier, sqlc.GamePhaseType, any) error) *Service_Advance_Call[T] {
	_c.Call.Return(run)
	return _c
}

// Perform provides a mock function with given fields: _a0, querier, move
func (_m *Service[T]) Perform(_a0 ctx.GameContext, querier db.Querier, move T) (any, error) {
	ret := _m.Called(_a0, querier, move)

	if len(ret) == 0 {
		panic("no return value specified for Perform")
	}

	var r0 any
	var r1 error
	if rf, ok := ret.Get(0).(func(ctx.GameContext, db.Querier, T) (any, error)); ok {
		return rf(_a0, querier, move)
	}
	if rf, ok := ret.Get(0).(func(ctx.GameContext, db.Querier, T) any); ok {
		r0 = rf(_a0, querier, move)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(any)
		}
	}

	if rf, ok := ret.Get(1).(func(ctx.GameContext, db.Querier, T) error); ok {
		r1 = rf(_a0, querier, move)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_Perform_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Perform'
type Service_Perform_Call[T any] struct {
	*mock.Call
}

// Perform is a helper method to define mock.On call
//   - _a0 ctx.GameContext
//   - querier db.Querier
//   - move T
func (_e *Service_Expecter[T]) Perform(_a0 interface{}, querier interface{}, move interface{}) *Service_Perform_Call[T] {
	return &Service_Perform_Call[T]{Call: _e.mock.On("Perform", _a0, querier, move)}
}

func (_c *Service_Perform_Call[T]) Run(run func(_a0 ctx.GameContext, querier db.Querier, move T)) *Service_Perform_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(ctx.GameContext), args[1].(db.Querier), args[2].(T))
	})
	return _c
}

func (_c *Service_Perform_Call[T]) Return(_a0 any, _a1 error) *Service_Perform_Call[T] {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_Perform_Call[T]) RunAndReturn(run func(ctx.GameContext, db.Querier, T) (any, error)) *Service_Perform_Call[T] {
	_c.Call.Return(run)
	return _c
}

// PhaseType provides a mock function with no fields
func (_m *Service[T]) PhaseType() sqlc.GamePhaseType {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for PhaseType")
	}

	var r0 sqlc.GamePhaseType
	if rf, ok := ret.Get(0).(func() sqlc.GamePhaseType); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(sqlc.GamePhaseType)
	}

	return r0
}

// Service_PhaseType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PhaseType'
type Service_PhaseType_Call[T any] struct {
	*mock.Call
}

// PhaseType is a helper method to define mock.On call
func (_e *Service_Expecter[T]) PhaseType() *Service_PhaseType_Call[T] {
	return &Service_PhaseType_Call[T]{Call: _e.mock.On("PhaseType")}
}

func (_c *Service_PhaseType_Call[T]) Run(run func()) *Service_PhaseType_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Service_PhaseType_Call[T]) Return(_a0 sqlc.GamePhaseType) *Service_PhaseType_Call[T] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Service_PhaseType_Call[T]) RunAndReturn(run func() sqlc.GamePhaseType) *Service_PhaseType_Call[T] {
	_c.Call.Return(run)
	return _c
}

// Walk provides a mock function with given fields: _a0, querier, voluntaryAdvancement
func (_m *Service[T]) Walk(_a0 ctx.GameContext, querier db.Querier, voluntaryAdvancement bool) (sqlc.GamePhaseType, error) {
	ret := _m.Called(_a0, querier, voluntaryAdvancement)

	if len(ret) == 0 {
		panic("no return value specified for Walk")
	}

	var r0 sqlc.GamePhaseType
	var r1 error
	if rf, ok := ret.Get(0).(func(ctx.GameContext, db.Querier, bool) (sqlc.GamePhaseType, error)); ok {
		return rf(_a0, querier, voluntaryAdvancement)
	}
	if rf, ok := ret.Get(0).(func(ctx.GameContext, db.Querier, bool) sqlc.GamePhaseType); ok {
		r0 = rf(_a0, querier, voluntaryAdvancement)
	} else {
		r0 = ret.Get(0).(sqlc.GamePhaseType)
	}

	if rf, ok := ret.Get(1).(func(ctx.GameContext, db.Querier, bool) error); ok {
		r1 = rf(_a0, querier, voluntaryAdvancement)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_Walk_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Walk'
type Service_Walk_Call[T any] struct {
	*mock.Call
}

// Walk is a helper method to define mock.On call
//   - _a0 ctx.GameContext
//   - querier db.Querier
//   - voluntaryAdvancement bool
func (_e *Service_Expecter[T]) Walk(_a0 interface{}, querier interface{}, voluntaryAdvancement interface{}) *Service_Walk_Call[T] {
	return &Service_Walk_Call[T]{Call: _e.mock.On("Walk", _a0, querier, voluntaryAdvancement)}
}

func (_c *Service_Walk_Call[T]) Run(run func(_a0 ctx.GameContext, querier db.Querier, voluntaryAdvancement bool)) *Service_Walk_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(ctx.GameContext), args[1].(db.Querier), args[2].(bool))
	})
	return _c
}

func (_c *Service_Walk_Call[T]) Return(_a0 sqlc.GamePhaseType, _a1 error) *Service_Walk_Call[T] {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_Walk_Call[T]) RunAndReturn(run func(ctx.GameContext, db.Querier, bool) (sqlc.GamePhaseType, error)) *Service_Walk_Call[T] {
	_c.Call.Return(run)
	return _c
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService[T any](t interface {
	mock.TestingT
	Cleanup(func())
}) *Service[T] {
	mock := &Service[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
