// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package data

import (
	"context"

	"github.com/jackc/pgx/v5"
	mock "github.com/stretchr/testify/mock"
)

// NewTxBeginner creates a new instance of TxBeginner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTxBeginner(t interface {
	mock.TestingT
	Cleanup(func())
}) *TxBeginner {
	mock := &TxBeginner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// TxBeginner is an autogenerated mock type for the TxBeginner type
type TxBeginner struct {
	mock.Mock
}

type TxBeginner_Expecter struct {
	mock *mock.Mock
}

func (_m *TxBeginner) EXPECT() *TxBeginner_Expecter {
	return &TxBeginner_Expecter{mock: &_m.Mock}
}

// BeginTx provides a mock function for the type TxBeginner
func (_mock *TxBeginner) BeginTx(ctx context.Context, txOptions pgx.TxOptions) (pgx.Tx, error) {
	ret := _mock.Called(ctx, txOptions)

	if len(ret) == 0 {
		panic("no return value specified for BeginTx")
	}

	var r0 pgx.Tx
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, pgx.TxOptions) (pgx.Tx, error)); ok {
		return returnFunc(ctx, txOptions)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, pgx.TxOptions) pgx.Tx); ok {
		r0 = returnFunc(ctx, txOptions)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(pgx.Tx)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, pgx.TxOptions) error); ok {
		r1 = returnFunc(ctx, txOptions)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TxBeginner_BeginTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BeginTx'
type TxBeginner_BeginTx_Call struct {
	*mock.Call
}

// BeginTx is a helper method to define mock.On call
//   - ctx context.Context
//   - txOptions pgx.TxOptions
func (_e *TxBeginner_Expecter) BeginTx(ctx interface{}, txOptions interface{}) *TxBeginner_BeginTx_Call {
	return &TxBeginner_BeginTx_Call{Call: _e.mock.On("BeginTx", ctx, txOptions)}
}

func (_c *TxBeginner_BeginTx_Call) Run(run func(ctx context.Context, txOptions pgx.TxOptions)) *TxBeginner_BeginTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 pgx.TxOptions
		if args[1] != nil {
			arg1 = args[1].(pgx.TxOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TxBeginner_BeginTx_Call) Return(tx pgx.Tx, err error) *TxBeginner_BeginTx_Call {
	_c.Call.Return(tx, err)
	return _c
}

func (_c *TxBeginner_BeginTx_Call) RunAndReturn(run func(ctx context.Context, txOptions pgx.TxOptions) (pgx.Tx, error)) *TxBeginner_BeginTx_Call {
	_c.Call.Return(run)
	return _c
}
