// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package events

import (
	"context"

	"github.com/go-risk-it/go-risk-it/internal/events"
	mock "github.com/stretchr/testify/mock"
)

// NewBus creates a new instance of Bus. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBus(t interface {
	mock.TestingT
	Cleanup(func())
}) *Bus {
	mock := &Bus{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Bus is an autogenerated mock type for the Bus type
type Bus struct {
	mock.Mock
}

type Bus_Expecter struct {
	mock *mock.Mock
}

func (_m *Bus) EXPECT() *Bus_Expecter {
	return &Bus_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type Bus
func (_mock *Bus) Close(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Bus_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type Bus_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Bus_Expecter) Close(ctx interface{}) *Bus_Close_Call {
	return &Bus_Close_Call{Call: _e.mock.On("Close", ctx)}
}

func (_c *Bus_Close_Call) Run(run func(ctx context.Context)) *Bus_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Bus_Close_Call) Return(err error) *Bus_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Bus_Close_Call) RunAndReturn(run func(ctx context.Context) error) *Bus_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Emit provides a mock function for the type Bus
func (_mock *Bus) Emit(ctx context.Context, event events.Event) {
	_mock.Called(ctx, event)
	return
}

// Bus_Emit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Emit'
type Bus_Emit_Call struct {
	*mock.Call
}

// Emit is a helper method to define mock.On call
//   - ctx context.Context
//   - event events.Event
func (_e *Bus_Expecter) Emit(ctx interface{}, event interface{}) *Bus_Emit_Call {
	return &Bus_Emit_Call{Call: _e.mock.On("Emit", ctx, event)}
}

func (_c *Bus_Emit_Call) Run(run func(ctx context.Context, event events.Event)) *Bus_Emit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 events.Event
		if args[1] != nil {
			arg1 = args[1].(events.Event)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Bus_Emit_Call) Return() *Bus_Emit_Call {
	_c.Call.Return()
	return _c
}

func (_c *Bus_Emit_Call) RunAndReturn(run func(ctx context.Context, event events.Event)) *Bus_Emit_Call {
	_c.Run(run)
	return _c
}

// OnAll provides a mock function for the type Bus
func (_mock *Bus) OnAll(handler events.Handler) {
	_mock.Called(handler)
	return
}

// Bus_OnAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnAll'
type Bus_OnAll_Call struct {
	*mock.Call
}

// OnAll is a helper method to define mock.On call
//   - handler events.Handler
func (_e *Bus_Expecter) OnAll(handler interface{}) *Bus_OnAll_Call {
	return &Bus_OnAll_Call{Call: _e.mock.On("OnAll", handler)}
}

func (_c *Bus_OnAll_Call) Run(run func(handler events.Handler)) *Bus_OnAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 events.Handler
		if args[0] != nil {
			arg0 = args[0].(events.Handler)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Bus_OnAll_Call) Return() *Bus_OnAll_Call {
	_c.Call.Return()
	return _c
}

func (_c *Bus_OnAll_Call) RunAndReturn(run func(handler events.Handler)) *Bus_OnAll_Call {
	_c.Run(run)
	return _c
}

// OnType provides a mock function for the type Bus
func (_mock *Bus) OnType(eventType string, handler events.Handler) {
	_mock.Called(eventType, handler)
	return
}

// Bus_OnType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnType'
type Bus_OnType_Call struct {
	*mock.Call
}

// OnType is a helper method to define mock.On call
//   - eventType string
//   - handler events.Handler
func (_e *Bus_Expecter) OnType(eventType interface{}, handler interface{}) *Bus_OnType_Call {
	return &Bus_OnType_Call{Call: _e.mock.On("OnType", eventType, handler)}
}

func (_c *Bus_OnType_Call) Run(run func(eventType string, handler events.Handler)) *Bus_OnType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 events.Handler
		if args[1] != nil {
			arg1 = args[1].(events.Handler)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Bus_OnType_Call) Return() *Bus_OnType_Call {
	_c.Call.Return()
	return _c
}

func (_c *Bus_OnType_Call) RunAndReturn(run func(eventType string, handler events.Handler)) *Bus_OnType_Call {
	_c.Run(run)
	return _c
}
