// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package orchestration

import (
	"github.com/go-risk-it/go-risk-it/internal/game/ctx"
	"github.com/go-risk-it/go-risk-it/internal/game/data/db"
	"github.com/go-risk-it/go-risk-it/internal/game/logic/state"
	mock "github.com/stretchr/testify/mock"
)

// NewValidationService creates a new instance of ValidationService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewValidationService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ValidationService {
	mock := &ValidationService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ValidationService is an autogenerated mock type for the ValidationService type
type ValidationService struct {
	mock.Mock
}

type ValidationService_Expecter struct {
	mock *mock.Mock
}

func (_m *ValidationService) EXPECT() *ValidationService_Expecter {
	return &ValidationService_Expecter{mock: &_m.Mock}
}

// Validate provides a mock function for the type ValidationService
func (_mock *ValidationService) Validate(ctx1 ctx.GameContext, querier db.Querier, game *state.Game) error {
	ret := _mock.Called(ctx1, querier, game)

	if len(ret) == 0 {
		panic("no return value specified for Validate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(ctx.GameContext, db.Querier, *state.Game) error); ok {
		r0 = returnFunc(ctx1, querier, game)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ValidationService_Validate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Validate'
type ValidationService_Validate_Call struct {
	*mock.Call
}

// Validate is a helper method to define mock.On call
//   - ctx1 ctx.GameContext
//   - querier db.Querier
//   - game *state.Game
func (_e *ValidationService_Expecter) Validate(ctx1 interface{}, querier interface{}, game interface{}) *ValidationService_Validate_Call {
	return &ValidationService_Validate_Call{Call: _e.mock.On("Validate", ctx1, querier, game)}
}

func (_c *ValidationService_Validate_Call) Run(run func(ctx1 ctx.GameContext, querier db.Querier, game *state.Game)) *ValidationService_Validate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 ctx.GameContext
		if args[0] != nil {
			arg0 = args[0].(ctx.GameContext)
		}
		var arg1 db.Querier
		if args[1] != nil {
			arg1 = args[1].(db.Querier)
		}
		var arg2 *state.Game
		if args[2] != nil {
			arg2 = args[2].(*state.Game)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ValidationService_Validate_Call) Return(err error) *ValidationService_Validate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ValidationService_Validate_Call) RunAndReturn(run func(ctx1 ctx.GameContext, querier db.Querier, game *state.Game) error) *ValidationService_Validate_Call {
	_c.Call.Return(run)
	return _c
}
