// Code generated by mockery v2.43.1. DO NOT EDIT.

package attack

import (
	ctx "github.com/go-risk-it/go-risk-it/internal/ctx"
	attack "github.com/go-risk-it/go-risk-it/internal/logic/game/move/performer/attack"

	db "github.com/go-risk-it/go-risk-it/internal/data/db"

	mock "github.com/stretchr/testify/mock"

	sqlc "github.com/go-risk-it/go-risk-it/internal/data/sqlc"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

type Service_Expecter struct {
	mock *mock.Mock
}

func (_m *Service) EXPECT() *Service_Expecter {
	return &Service_Expecter{mock: &_m.Mock}
}

// ContinueAttackQ provides a mock function with given fields:
func (_m *Service) ContinueAttackQ() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ContinueAttackQ")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Service_ContinueAttackQ_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ContinueAttackQ'
type Service_ContinueAttackQ_Call struct {
	*mock.Call
}

// ContinueAttackQ is a helper method to define mock.On call
func (_e *Service_Expecter) ContinueAttackQ() *Service_ContinueAttackQ_Call {
	return &Service_ContinueAttackQ_Call{Call: _e.mock.On("ContinueAttackQ")}
}

func (_c *Service_ContinueAttackQ_Call) Run(run func()) *Service_ContinueAttackQ_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Service_ContinueAttackQ_Call) Return(_a0 bool) *Service_ContinueAttackQ_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Service_ContinueAttackQ_Call) RunAndReturn(run func() bool) *Service_ContinueAttackQ_Call {
	_c.Call.Return(run)
	return _c
}

// HasConqueredQ provides a mock function with given fields:
func (_m *Service) HasConqueredQ() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for HasConqueredQ")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Service_HasConqueredQ_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasConqueredQ'
type Service_HasConqueredQ_Call struct {
	*mock.Call
}

// HasConqueredQ is a helper method to define mock.On call
func (_e *Service_Expecter) HasConqueredQ() *Service_HasConqueredQ_Call {
	return &Service_HasConqueredQ_Call{Call: _e.mock.On("HasConqueredQ")}
}

func (_c *Service_HasConqueredQ_Call) Run(run func()) *Service_HasConqueredQ_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Service_HasConqueredQ_Call) Return(_a0 bool) *Service_HasConqueredQ_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Service_HasConqueredQ_Call) RunAndReturn(run func() bool) *Service_HasConqueredQ_Call {
	_c.Call.Return(run)
	return _c
}

// MustAdvanceQ provides a mock function with given fields: _a0, querier, game
func (_m *Service) MustAdvanceQ(_a0 ctx.MoveContext, querier db.Querier, game *sqlc.Game) bool {
	ret := _m.Called(_a0, querier, game)

	if len(ret) == 0 {
		panic("no return value specified for MustAdvanceQ")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(ctx.MoveContext, db.Querier, *sqlc.Game) bool); ok {
		r0 = rf(_a0, querier, game)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Service_MustAdvanceQ_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MustAdvanceQ'
type Service_MustAdvanceQ_Call struct {
	*mock.Call
}

// MustAdvanceQ is a helper method to define mock.On call
//   - _a0 ctx.MoveContext
//   - querier db.Querier
//   - game *sqlc.Game
func (_e *Service_Expecter) MustAdvanceQ(_a0 interface{}, querier interface{}, game interface{}) *Service_MustAdvanceQ_Call {
	return &Service_MustAdvanceQ_Call{Call: _e.mock.On("MustAdvanceQ", _a0, querier, game)}
}

func (_c *Service_MustAdvanceQ_Call) Run(run func(_a0 ctx.MoveContext, querier db.Querier, game *sqlc.Game)) *Service_MustAdvanceQ_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(ctx.MoveContext), args[1].(db.Querier), args[2].(*sqlc.Game))
	})
	return _c
}

func (_c *Service_MustAdvanceQ_Call) Return(_a0 bool) *Service_MustAdvanceQ_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Service_MustAdvanceQ_Call) RunAndReturn(run func(ctx.MoveContext, db.Querier, *sqlc.Game) bool) *Service_MustAdvanceQ_Call {
	_c.Call.Return(run)
	return _c
}

// PerformQ provides a mock function with given fields: _a0, querier, game, move
func (_m *Service) PerformQ(_a0 ctx.MoveContext, querier db.Querier, game *sqlc.Game, move attack.Move) error {
	ret := _m.Called(_a0, querier, game, move)

	if len(ret) == 0 {
		panic("no return value specified for PerformQ")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(ctx.MoveContext, db.Querier, *sqlc.Game, attack.Move) error); ok {
		r0 = rf(_a0, querier, game, move)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Service_PerformQ_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PerformQ'
type Service_PerformQ_Call struct {
	*mock.Call
}

// PerformQ is a helper method to define mock.On call
//   - _a0 ctx.MoveContext
//   - querier db.Querier
//   - game *sqlc.Game
//   - move attack.Move
func (_e *Service_Expecter) PerformQ(_a0 interface{}, querier interface{}, game interface{}, move interface{}) *Service_PerformQ_Call {
	return &Service_PerformQ_Call{Call: _e.mock.On("PerformQ", _a0, querier, game, move)}
}

func (_c *Service_PerformQ_Call) Run(run func(_a0 ctx.MoveContext, querier db.Querier, game *sqlc.Game, move attack.Move)) *Service_PerformQ_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(ctx.MoveContext), args[1].(db.Querier), args[2].(*sqlc.Game), args[3].(attack.Move))
	})
	return _c
}

func (_c *Service_PerformQ_Call) Return(_a0 error) *Service_PerformQ_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Service_PerformQ_Call) RunAndReturn(run func(ctx.MoveContext, db.Querier, *sqlc.Game, attack.Move) error) *Service_PerformQ_Call {
	_c.Call.Return(run)
	return _c
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
