database:
  host: ${DATABASE_HOST}
  port: ${DATABASE_PORT}
  name: ${DATABASE_NAME}
  user: ${DATABASE_USER}
  password: ${DATABASE_PASSWORD}
  disable_ssl: true

jwt:
  secret: ${JWT_SECRET}

dice:
  roll_strategy: attacker_always_wins

regionassignment:
  assignment_strategy: sequential

history:
  size: 999

otel:
  enabled: true