database:
  host: ${DATABASE_HOST}
  port: ${DATABASE_PORT}
  name: ${DATABASE_NAME}
  user: ${DATABASE_USER}
  password: ${DATABASE_PASSWORD}
  disable_ssl: false

jwt:
  secret: ${JWT_SECRET}

tls:
  cert: ${TLS_CERT}
  key: ${TLS_KEY}
  insecure_skip_verify: false

dice:
  roll_strategy: random

history:
  size: 50