database:
  host: ${DATABASE_HOST}
  port: ${DATABASE_PORT}
  name: ${DATABASE_NAME}
  user: ${DATABASE_USER}
  password: ${DATABASE_PASSWORD}
  disable_ssl: false

jwt:
  secret: ${JWT_SECRET}

dice:
  roll_strategy: random

history:
  size: 50