// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package card

import (
	"github.com/go-risk-it/go-risk-it/internal/game/ctx"
	"github.com/go-risk-it/go-risk-it/internal/game/internal/data/db"
	"github.com/go-risk-it/go-risk-it/internal/game/internal/data/sqlc"
	mock "github.com/stretchr/testify/mock"
)

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

type Service_Expecter struct {
	mock *mock.Mock
}

func (_m *Service) EXPECT() *Service_Expecter {
	return &Service_Expecter{mock: &_m.Mock}
}

// CreateCards provides a mock function for the type Service
func (_mock *Service) CreateCards(ctx1 ctx.GameContext, querier db.Querier) error {
	ret := _mock.Called(ctx1, querier)

	if len(ret) == 0 {
		panic("no return value specified for CreateCards")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(ctx.GameContext, db.Querier) error); ok {
		r0 = returnFunc(ctx1, querier)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Service_CreateCards_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateCards'
type Service_CreateCards_Call struct {
	*mock.Call
}

// CreateCards is a helper method to define mock.On call
//   - ctx1 ctx.GameContext
//   - querier db.Querier
func (_e *Service_Expecter) CreateCards(ctx1 interface{}, querier interface{}) *Service_CreateCards_Call {
	return &Service_CreateCards_Call{Call: _e.mock.On("CreateCards", ctx1, querier)}
}

func (_c *Service_CreateCards_Call) Run(run func(ctx1 ctx.GameContext, querier db.Querier)) *Service_CreateCards_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 ctx.GameContext
		if args[0] != nil {
			arg0 = args[0].(ctx.GameContext)
		}
		var arg1 db.Querier
		if args[1] != nil {
			arg1 = args[1].(db.Querier)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Service_CreateCards_Call) Return(err error) *Service_CreateCards_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Service_CreateCards_Call) RunAndReturn(run func(ctx1 ctx.GameContext, querier db.Querier) error) *Service_CreateCards_Call {
	_c.Call.Return(run)
	return _c
}

// GetCardsForPlayer provides a mock function for the type Service
func (_mock *Service) GetCardsForPlayer(ctx1 ctx.GameContext) ([]sqlc.GetCardsForPlayerRow, error) {
	ret := _mock.Called(ctx1)

	if len(ret) == 0 {
		panic("no return value specified for GetCardsForPlayer")
	}

	var r0 []sqlc.GetCardsForPlayerRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(ctx.GameContext) ([]sqlc.GetCardsForPlayerRow, error)); ok {
		return returnFunc(ctx1)
	}
	if returnFunc, ok := ret.Get(0).(func(ctx.GameContext) []sqlc.GetCardsForPlayerRow); ok {
		r0 = returnFunc(ctx1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]sqlc.GetCardsForPlayerRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(ctx.GameContext) error); ok {
		r1 = returnFunc(ctx1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Service_GetCardsForPlayer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCardsForPlayer'
type Service_GetCardsForPlayer_Call struct {
	*mock.Call
}

// GetCardsForPlayer is a helper method to define mock.On call
//   - ctx1 ctx.GameContext
func (_e *Service_Expecter) GetCardsForPlayer(ctx1 interface{}) *Service_GetCardsForPlayer_Call {
	return &Service_GetCardsForPlayer_Call{Call: _e.mock.On("GetCardsForPlayer", ctx1)}
}

func (_c *Service_GetCardsForPlayer_Call) Run(run func(ctx1 ctx.GameContext)) *Service_GetCardsForPlayer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 ctx.GameContext
		if args[0] != nil {
			arg0 = args[0].(ctx.GameContext)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Service_GetCardsForPlayer_Call) Return(getCardsForPlayerRows []sqlc.GetCardsForPlayerRow, err error) *Service_GetCardsForPlayer_Call {
	_c.Call.Return(getCardsForPlayerRows, err)
	return _c
}

func (_c *Service_GetCardsForPlayer_Call) RunAndReturn(run func(ctx1 ctx.GameContext) ([]sqlc.GetCardsForPlayerRow, error)) *Service_GetCardsForPlayer_Call {
	_c.Call.Return(run)
	return _c
}

// GetCardsForPlayerWithQuerier provides a mock function for the type Service
func (_mock *Service) GetCardsForPlayerWithQuerier(ctx1 ctx.GameContext, querier db.Querier) ([]sqlc.GetCardsForPlayerRow, error) {
	ret := _mock.Called(ctx1, querier)

	if len(ret) == 0 {
		panic("no return value specified for GetCardsForPlayerWithQuerier")
	}

	var r0 []sqlc.GetCardsForPlayerRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(ctx.GameContext, db.Querier) ([]sqlc.GetCardsForPlayerRow, error)); ok {
		return returnFunc(ctx1, querier)
	}
	if returnFunc, ok := ret.Get(0).(func(ctx.GameContext, db.Querier) []sqlc.GetCardsForPlayerRow); ok {
		r0 = returnFunc(ctx1, querier)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]sqlc.GetCardsForPlayerRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(ctx.GameContext, db.Querier) error); ok {
		r1 = returnFunc(ctx1, querier)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Service_GetCardsForPlayerWithQuerier_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCardsForPlayerWithQuerier'
type Service_GetCardsForPlayerWithQuerier_Call struct {
	*mock.Call
}

// GetCardsForPlayerWithQuerier is a helper method to define mock.On call
//   - ctx1 ctx.GameContext
//   - querier db.Querier
func (_e *Service_Expecter) GetCardsForPlayerWithQuerier(ctx1 interface{}, querier interface{}) *Service_GetCardsForPlayerWithQuerier_Call {
	return &Service_GetCardsForPlayerWithQuerier_Call{Call: _e.mock.On("GetCardsForPlayerWithQuerier", ctx1, querier)}
}

func (_c *Service_GetCardsForPlayerWithQuerier_Call) Run(run func(ctx1 ctx.GameContext, querier db.Querier)) *Service_GetCardsForPlayerWithQuerier_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 ctx.GameContext
		if args[0] != nil {
			arg0 = args[0].(ctx.GameContext)
		}
		var arg1 db.Querier
		if args[1] != nil {
			arg1 = args[1].(db.Querier)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Service_GetCardsForPlayerWithQuerier_Call) Return(getCardsForPlayerRows []sqlc.GetCardsForPlayerRow, err error) *Service_GetCardsForPlayerWithQuerier_Call {
	_c.Call.Return(getCardsForPlayerRows, err)
	return _c
}

func (_c *Service_GetCardsForPlayerWithQuerier_Call) RunAndReturn(run func(ctx1 ctx.GameContext, querier db.Querier) ([]sqlc.GetCardsForPlayerRow, error)) *Service_GetCardsForPlayerWithQuerier_Call {
	_c.Call.Return(run)
	return _c
}

// TransferCardsOwnership provides a mock function for the type Service
func (_mock *Service) TransferCardsOwnership(ctx1 ctx.GameContext, querier db.Querier, defendingPlayerID int64) error {
	ret := _mock.Called(ctx1, querier, defendingPlayerID)

	if len(ret) == 0 {
		panic("no return value specified for TransferCardsOwnership")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(ctx.GameContext, db.Querier, int64) error); ok {
		r0 = returnFunc(ctx1, querier, defendingPlayerID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Service_TransferCardsOwnership_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TransferCardsOwnership'
type Service_TransferCardsOwnership_Call struct {
	*mock.Call
}

// TransferCardsOwnership is a helper method to define mock.On call
//   - ctx1 ctx.GameContext
//   - querier db.Querier
//   - defendingPlayerID int64
func (_e *Service_Expecter) TransferCardsOwnership(ctx1 interface{}, querier interface{}, defendingPlayerID interface{}) *Service_TransferCardsOwnership_Call {
	return &Service_TransferCardsOwnership_Call{Call: _e.mock.On("TransferCardsOwnership", ctx1, querier, defendingPlayerID)}
}

func (_c *Service_TransferCardsOwnership_Call) Run(run func(ctx1 ctx.GameContext, querier db.Querier, defendingPlayerID int64)) *Service_TransferCardsOwnership_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 ctx.GameContext
		if args[0] != nil {
			arg0 = args[0].(ctx.GameContext)
		}
		var arg1 db.Querier
		if args[1] != nil {
			arg1 = args[1].(db.Querier)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Service_TransferCardsOwnership_Call) Return(err error) *Service_TransferCardsOwnership_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Service_TransferCardsOwnership_Call) RunAndReturn(run func(ctx1 ctx.GameContext, querier db.Querier, defendingPlayerID int64) error) *Service_TransferCardsOwnership_Call {
	_c.Call.Return(run)
	return _c
}
