// Code generated by mockery v2.43.1. DO NOT EDIT.

package deploy

import (
	ctx "github.com/go-risk-it/go-risk-it/internal/ctx"
	db "github.com/go-risk-it/go-risk-it/internal/data/db"

	deploy "github.com/go-risk-it/go-risk-it/internal/logic/game/move/performer/deploy"

	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

type Service_Expecter struct {
	mock *mock.Mock
}

func (_m *Service) EXPECT() *Service_Expecter {
	return &Service_Expecter{mock: &_m.Mock}
}

// GetDeployableTroops provides a mock function with given fields: _a0, querier
func (_m *Service) GetDeployableTroops(_a0 ctx.MoveContext, querier db.Querier) (int64, error) {
	ret := _m.Called(_a0, querier)

	if len(ret) == 0 {
		panic("no return value specified for GetDeployableTroops")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(ctx.MoveContext, db.Querier) (int64, error)); ok {
		return rf(_a0, querier)
	}
	if rf, ok := ret.Get(0).(func(ctx.MoveContext, db.Querier) int64); ok {
		r0 = rf(_a0, querier)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(ctx.MoveContext, db.Querier) error); ok {
		r1 = rf(_a0, querier)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_GetDeployableTroops_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDeployableTroops'
type Service_GetDeployableTroops_Call struct {
	*mock.Call
}

// GetDeployableTroops is a helper method to define mock.On call
//   - _a0 ctx.MoveContext
//   - querier db.Querier
func (_e *Service_Expecter) GetDeployableTroops(_a0 interface{}, querier interface{}) *Service_GetDeployableTroops_Call {
	return &Service_GetDeployableTroops_Call{Call: _e.mock.On("GetDeployableTroops", _a0, querier)}
}

func (_c *Service_GetDeployableTroops_Call) Run(run func(_a0 ctx.MoveContext, querier db.Querier)) *Service_GetDeployableTroops_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(ctx.MoveContext), args[1].(db.Querier))
	})
	return _c
}

func (_c *Service_GetDeployableTroops_Call) Return(_a0 int64, _a1 error) *Service_GetDeployableTroops_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_GetDeployableTroops_Call) RunAndReturn(run func(ctx.MoveContext, db.Querier) (int64, error)) *Service_GetDeployableTroops_Call {
	_c.Call.Return(run)
	return _c
}

// PerformQ provides a mock function with given fields: _a0, querier, move
func (_m *Service) PerformQ(_a0 ctx.MoveContext, querier db.Querier, move deploy.Move) error {
	ret := _m.Called(_a0, querier, move)

	if len(ret) == 0 {
		panic("no return value specified for PerformQ")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(ctx.MoveContext, db.Querier, deploy.Move) error); ok {
		r0 = rf(_a0, querier, move)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Service_PerformQ_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PerformQ'
type Service_PerformQ_Call struct {
	*mock.Call
}

// PerformQ is a helper method to define mock.On call
//   - _a0 ctx.MoveContext
//   - querier db.Querier
//   - move deploy.Move
func (_e *Service_Expecter) PerformQ(_a0 interface{}, querier interface{}, move interface{}) *Service_PerformQ_Call {
	return &Service_PerformQ_Call{Call: _e.mock.On("PerformQ", _a0, querier, move)}
}

func (_c *Service_PerformQ_Call) Run(run func(_a0 ctx.MoveContext, querier db.Querier, move deploy.Move)) *Service_PerformQ_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(ctx.MoveContext), args[1].(db.Querier), args[2].(deploy.Move))
	})
	return _c
}

func (_c *Service_PerformQ_Call) Return(_a0 error) *Service_PerformQ_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Service_PerformQ_Call) RunAndReturn(run func(ctx.MoveContext, db.Querier, deploy.Move) error) *Service_PerformQ_Call {
	_c.Call.Return(run)
	return _c
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
