// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package snapshot

import (
	"github.com/go-risk-it/go-risk-it/internal/game/logic/snapshot"
	"github.com/go-risk-it/go-risk-it/internal/kernel/ctx"
	mock "github.com/stretchr/testify/mock"
)

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

type Service_Expecter struct {
	mock *mock.Mock
}

func (_m *Service) EXPECT() *Service_Expecter {
	return &Service_Expecter{mock: &_m.Mock}
}

// GetPrivateSnapshotsByUser provides a mock function for the type Service
func (_mock *Service) GetPrivateSnapshotsByUser(ctx1 ctx.GameContext) (map[string]*snapshot.PrivateSnapshot, error) {
	ret := _mock.Called(ctx1)

	if len(ret) == 0 {
		panic("no return value specified for GetPrivateSnapshotsByUser")
	}

	var r0 map[string]*snapshot.PrivateSnapshot
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(ctx.GameContext) (map[string]*snapshot.PrivateSnapshot, error)); ok {
		return returnFunc(ctx1)
	}
	if returnFunc, ok := ret.Get(0).(func(ctx.GameContext) map[string]*snapshot.PrivateSnapshot); ok {
		r0 = returnFunc(ctx1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]*snapshot.PrivateSnapshot)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(ctx.GameContext) error); ok {
		r1 = returnFunc(ctx1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Service_GetPrivateSnapshotsByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPrivateSnapshotsByUser'
type Service_GetPrivateSnapshotsByUser_Call struct {
	*mock.Call
}

// GetPrivateSnapshotsByUser is a helper method to define mock.On call
//   - ctx1 ctx.GameContext
func (_e *Service_Expecter) GetPrivateSnapshotsByUser(ctx1 interface{}) *Service_GetPrivateSnapshotsByUser_Call {
	return &Service_GetPrivateSnapshotsByUser_Call{Call: _e.mock.On("GetPrivateSnapshotsByUser", ctx1)}
}

func (_c *Service_GetPrivateSnapshotsByUser_Call) Run(run func(ctx1 ctx.GameContext)) *Service_GetPrivateSnapshotsByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 ctx.GameContext
		if args[0] != nil {
			arg0 = args[0].(ctx.GameContext)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Service_GetPrivateSnapshotsByUser_Call) Return(stringToPrivateSnapshot map[string]*snapshot.PrivateSnapshot, err error) *Service_GetPrivateSnapshotsByUser_Call {
	_c.Call.Return(stringToPrivateSnapshot, err)
	return _c
}

func (_c *Service_GetPrivateSnapshotsByUser_Call) RunAndReturn(run func(ctx1 ctx.GameContext) (map[string]*snapshot.PrivateSnapshot, error)) *Service_GetPrivateSnapshotsByUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetPublicSnapshot provides a mock function for the type Service
func (_mock *Service) GetPublicSnapshot(ctx1 ctx.GameContext) (*snapshot.PublicSnapshot, error) {
	ret := _mock.Called(ctx1)

	if len(ret) == 0 {
		panic("no return value specified for GetPublicSnapshot")
	}

	var r0 *snapshot.PublicSnapshot
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(ctx.GameContext) (*snapshot.PublicSnapshot, error)); ok {
		return returnFunc(ctx1)
	}
	if returnFunc, ok := ret.Get(0).(func(ctx.GameContext) *snapshot.PublicSnapshot); ok {
		r0 = returnFunc(ctx1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*snapshot.PublicSnapshot)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(ctx.GameContext) error); ok {
		r1 = returnFunc(ctx1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Service_GetPublicSnapshot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPublicSnapshot'
type Service_GetPublicSnapshot_Call struct {
	*mock.Call
}

// GetPublicSnapshot is a helper method to define mock.On call
//   - ctx1 ctx.GameContext
func (_e *Service_Expecter) GetPublicSnapshot(ctx1 interface{}) *Service_GetPublicSnapshot_Call {
	return &Service_GetPublicSnapshot_Call{Call: _e.mock.On("GetPublicSnapshot", ctx1)}
}

func (_c *Service_GetPublicSnapshot_Call) Run(run func(ctx1 ctx.GameContext)) *Service_GetPublicSnapshot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 ctx.GameContext
		if args[0] != nil {
			arg0 = args[0].(ctx.GameContext)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Service_GetPublicSnapshot_Call) Return(publicSnapshot *snapshot.PublicSnapshot, err error) *Service_GetPublicSnapshot_Call {
	_c.Call.Return(publicSnapshot, err)
	return _c
}

func (_c *Service_GetPublicSnapshot_Call) RunAndReturn(run func(ctx1 ctx.GameContext) (*snapshot.PublicSnapshot, error)) *Service_GetPublicSnapshot_Call {
	_c.Call.Return(run)
	return _c
}
