// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package orchestration

import (
	"github.com/go-risk-it/go-risk-it/internal/game/ctx"
	"github.com/go-risk-it/go-risk-it/internal/game/internal/logic/move/cards"
	mock "github.com/stretchr/testify/mock"
)

// NewCardsOrchestrator creates a new instance of CardsOrchestrator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCardsOrchestrator(t interface {
	mock.TestingT
	Cleanup(func())
}) *CardsOrchestrator {
	mock := &CardsOrchestrator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// CardsOrchestrator is an autogenerated mock type for the CardsOrchestrator type
type CardsOrchestrator struct {
	mock.Mock
}

type CardsOrchestrator_Expecter struct {
	mock *mock.Mock
}

func (_m *CardsOrchestrator) EXPECT() *CardsOrchestrator_Expecter {
	return &CardsOrchestrator_Expecter{mock: &_m.Mock}
}

// OrchestrateMove provides a mock function for the type CardsOrchestrator
func (_mock *CardsOrchestrator) OrchestrateMove(ctx1 ctx.GameContext, move cards.Move) error {
	ret := _mock.Called(ctx1, move)

	if len(ret) == 0 {
		panic("no return value specified for OrchestrateMove")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(ctx.GameContext, cards.Move) error); ok {
		r0 = returnFunc(ctx1, move)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// CardsOrchestrator_OrchestrateMove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OrchestrateMove'
type CardsOrchestrator_OrchestrateMove_Call struct {
	*mock.Call
}

// OrchestrateMove is a helper method to define mock.On call
//   - ctx1 ctx.GameContext
//   - move cards.Move
func (_e *CardsOrchestrator_Expecter) OrchestrateMove(ctx1 interface{}, move interface{}) *CardsOrchestrator_OrchestrateMove_Call {
	return &CardsOrchestrator_OrchestrateMove_Call{Call: _e.mock.On("OrchestrateMove", ctx1, move)}
}

func (_c *CardsOrchestrator_OrchestrateMove_Call) Run(run func(ctx1 ctx.GameContext, move cards.Move)) *CardsOrchestrator_OrchestrateMove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 ctx.GameContext
		if args[0] != nil {
			arg0 = args[0].(ctx.GameContext)
		}
		var arg1 cards.Move
		if args[1] != nil {
			arg1 = args[1].(cards.Move)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CardsOrchestrator_OrchestrateMove_Call) Return(err error) *CardsOrchestrator_OrchestrateMove_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *CardsOrchestrator_OrchestrateMove_Call) RunAndReturn(run func(ctx1 ctx.GameContext, move cards.Move) error) *CardsOrchestrator_OrchestrateMove_Call {
	_c.Call.Return(run)
	return _c
}
