// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package db

import ()

type Card struct {
	ID       int64
	PlayerID int64
}

type Game struct {
	ID          int64
	CurrentTurn int64
}

type Mission struct {
	ID       int64
	PlayerID int64
}

type Player struct {
	ID        int64
	GameID    int64
	UserID    string
	TurnIndex int64
}

type Region struct {
	ID       int64
	PlayerID int64
	Troops   int32
}
