name: Component tests

on:
  push:
    branches:
      - main
    tags:
      - "*"

env:
  DEFAULT_PYTHON_VERSION: "3.11"
  POETRY_VERSION: "1.8.5"

jobs:
  test:
    name: Component tests
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout git repository
        uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98

      - name: Set up Python ${{ env.DEFAULT_PYTHON_VERSION }}
        uses: actions/setup-python@28f2168f4d98ee0445e3c6321f6e6616c83dd5ec
        with:
          python-version: ${{ env.DEFAULT_PYTHON_VERSION }}

      - name: Install poetry
        uses: Gr1N/setup-poetry@48b0f77c8c1b1b19cb962f0f00dff7b4be8f81ec # v9
        with:
          poetry-version: ${{ env.POETRY_VERSION }}

      - name: Load Poetry Cached Libraries
        id: cache-poetry
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7
        with:
          path: component-test/.venv
          key: ${{ runner.os }}-poetry-${{ env.POETRY_VERSION }}-${{ env.DEFAULT_PYTHON_VERSION }}-${{ hashFiles('component-test/poetry.lock') }}

      - name: Configure virtual environment
        run: poetry config virtualenvs.in-project true
        working-directory: component-test

      - name: Install Dependencies
        run: poetry install
        working-directory: component-test

      - name: Test Code
        run: poetry run behave
        working-directory: component-test
