name: Visualizer

on:
  push:
    branches: [ "main" ]
  merge_group:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Repo Visualizer
      uses: githubocto/repo-visualizer@0.9.1
      with:
        output_file: "docs/repo.svg"
        excluded_paths: "mocks,docs,supabase"
            
