name: Visualizer

on:
  push:
    branches: [ "main" ]
  merge_group:

jobs:
  update_diagram:
    name: Update the codebase structure diagram
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4

      - name: Update diagram
        uses: githubocto/repo-visualizer@main
        with:
          excluded_paths: "component-test,docs,mocks,supabase"
          output_file: codebase-structure.svg
          should_push: false

      - name: Generate PR for updates
        uses: peter-evans/create-pull-request@c5a7806660adbe173f04e3e038b0ccdcd758773c # v6
        with:
          commit-message: 'ci: update repo-visualizer diagram'
          signoff: true
          branch: ci_update_diagram
          delete-branch: true
          title: 'ci: update repo-visualizer diagram'
          add-paths: |
            codebase-structure.svg
